// Code generated by ent, DO NOT EDIT.

package withdrawalevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the withdrawalevent type in the database.
	Label = "withdrawal_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWithdrawalID holds the string denoting the withdrawal_id field in the database.
	FieldWithdrawalID = "withdrawal_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldFromStatus holds the string denoting the from_status field in the database.
	FieldFromStatus = "from_status"
	// FieldToStatus holds the string denoting the to_status field in the database.
	FieldToStatus = "to_status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeWithdrawal holds the string denoting the withdrawal edge name in mutations.
	EdgeWithdrawal = "withdrawal"
	// Table holds the table name of the withdrawalevent in the database.
	Table = "withdrawal_events"
	// WithdrawalTable is the table that holds the withdrawal relation/edge.
	WithdrawalTable = "withdrawal_events"
	// WithdrawalInverseTable is the table name for the Withdrawal entity.
	// It exists in this package in order to avoid circular dependency with the "withdrawal" package.
	WithdrawalInverseTable = "withdrawals"
	// WithdrawalColumn is the table column denoting the withdrawal relation/edge.
	WithdrawalColumn = "withdrawal_id"
)

// Columns holds all SQL columns for withdrawalevent fields.
var Columns = []string{
	FieldID,
	FieldWithdrawalID,
	FieldEventType,
	FieldFromStatus,
	FieldToStatus,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// FromStatusValidator is a validator for the "from_status" field. It is called by the builders before save.
	FromStatusValidator func(string) error
	// ToStatusValidator is a validator for the "to_status" field. It is called by the builders before save.
	ToStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the WithdrawalEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWithdrawalID orders the results by the withdrawal_id field.
func ByWithdrawalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWithdrawalID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByFromStatus orders the results by the from_status field.
func ByFromStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromStatus, opts...).ToFunc()
}

// ByToStatus orders the results by the to_status field.
func ByToStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByWithdrawalField orders the results by withdrawal field.
func ByWithdrawalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWithdrawalStep(), sql.OrderByField(field, opts...))
	}
}
func newWithdrawalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WithdrawalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WithdrawalTable, WithdrawalColumn),
	)
}
