// Code generated by ent, DO NOT EDIT.

package depositevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the depositevent type in the database.
	Label = "deposit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepositID holds the string denoting the deposit_id field in the database.
	FieldDepositID = "deposit_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldFromStatus holds the string denoting the from_status field in the database.
	FieldFromStatus = "from_status"
	// FieldToStatus holds the string denoting the to_status field in the database.
	FieldToStatus = "to_status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDeposit holds the string denoting the deposit edge name in mutations.
	EdgeDeposit = "deposit"
	// Table holds the table name of the depositevent in the database.
	Table = "deposit_events"
	// DepositTable is the table that holds the deposit relation/edge.
	DepositTable = "deposit_events"
	// DepositInverseTable is the table name for the Deposit entity.
	// It exists in this package in order to avoid circular dependency with the "deposit" package.
	DepositInverseTable = "deposits"
	// DepositColumn is the table column denoting the deposit relation/edge.
	DepositColumn = "deposit_id"
)

// Columns holds all SQL columns for depositevent fields.
var Columns = []string{
	FieldID,
	FieldDepositID,
	FieldEventType,
	FieldFromStatus,
	FieldToStatus,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// FromStatusValidator is a validator for the "from_status" field. It is called by the builders before save.
	FromStatusValidator func(string) error
	// ToStatusValidator is a validator for the "to_status" field. It is called by the builders before save.
	ToStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the DepositEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDepositID orders the results by the deposit_id field.
func ByDepositID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepositID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByFromStatus orders the results by the from_status field.
func ByFromStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromStatus, opts...).ToFunc()
}

// ByToStatus orders the results by the to_status field.
func ByToStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDepositField orders the results by deposit field.
func ByDepositField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDepositStep(), sql.OrderByField(field, opts...))
	}
}
func newDepositStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DepositInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DepositTable, DepositColumn),
	)
}
