// Code generated by ent, DO NOT EDIT.

package depositevent

import (
	"crypto-payment-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContainsFold(FieldID, id))
}

// DepositID applies equality check predicate on the "deposit_id" field. It's identical to DepositIDEQ.
func DepositID(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldDepositID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldEventType, v))
}

// FromStatus applies equality check predicate on the "from_status" field. It's identical to FromStatusEQ.
func FromStatus(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldFromStatus, v))
}

// ToStatus applies equality check predicate on the "to_status" field. It's identical to ToStatusEQ.
func ToStatus(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldToStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// DepositIDEQ applies the EQ predicate on the "deposit_id" field.
func DepositIDEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldDepositID, v))
}

// DepositIDNEQ applies the NEQ predicate on the "deposit_id" field.
func DepositIDNEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNEQ(FieldDepositID, v))
}

// DepositIDIn applies the In predicate on the "deposit_id" field.
func DepositIDIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIn(FieldDepositID, vs...))
}

// DepositIDNotIn applies the NotIn predicate on the "deposit_id" field.
func DepositIDNotIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotIn(FieldDepositID, vs...))
}

// DepositIDGT applies the GT predicate on the "deposit_id" field.
func DepositIDGT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGT(FieldDepositID, v))
}

// DepositIDGTE applies the GTE predicate on the "deposit_id" field.
func DepositIDGTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGTE(FieldDepositID, v))
}

// DepositIDLT applies the LT predicate on the "deposit_id" field.
func DepositIDLT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLT(FieldDepositID, v))
}

// DepositIDLTE applies the LTE predicate on the "deposit_id" field.
func DepositIDLTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLTE(FieldDepositID, v))
}

// DepositIDContains applies the Contains predicate on the "deposit_id" field.
func DepositIDContains(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContains(FieldDepositID, v))
}

// DepositIDHasPrefix applies the HasPrefix predicate on the "deposit_id" field.
func DepositIDHasPrefix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasPrefix(FieldDepositID, v))
}

// DepositIDHasSuffix applies the HasSuffix predicate on the "deposit_id" field.
func DepositIDHasSuffix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasSuffix(FieldDepositID, v))
}

// DepositIDEqualFold applies the EqualFold predicate on the "deposit_id" field.
func DepositIDEqualFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEqualFold(FieldDepositID, v))
}

// DepositIDContainsFold applies the ContainsFold predicate on the "deposit_id" field.
func DepositIDContainsFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContainsFold(FieldDepositID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContainsFold(FieldEventType, v))
}

// FromStatusEQ applies the EQ predicate on the "from_status" field.
func FromStatusEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldFromStatus, v))
}

// FromStatusNEQ applies the NEQ predicate on the "from_status" field.
func FromStatusNEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNEQ(FieldFromStatus, v))
}

// FromStatusIn applies the In predicate on the "from_status" field.
func FromStatusIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIn(FieldFromStatus, vs...))
}

// FromStatusNotIn applies the NotIn predicate on the "from_status" field.
func FromStatusNotIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotIn(FieldFromStatus, vs...))
}

// FromStatusGT applies the GT predicate on the "from_status" field.
func FromStatusGT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGT(FieldFromStatus, v))
}

// FromStatusGTE applies the GTE predicate on the "from_status" field.
func FromStatusGTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGTE(FieldFromStatus, v))
}

// FromStatusLT applies the LT predicate on the "from_status" field.
func FromStatusLT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLT(FieldFromStatus, v))
}

// FromStatusLTE applies the LTE predicate on the "from_status" field.
func FromStatusLTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLTE(FieldFromStatus, v))
}

// FromStatusContains applies the Contains predicate on the "from_status" field.
func FromStatusContains(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContains(FieldFromStatus, v))
}

// FromStatusHasPrefix applies the HasPrefix predicate on the "from_status" field.
func FromStatusHasPrefix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasPrefix(FieldFromStatus, v))
}

// FromStatusHasSuffix applies the HasSuffix predicate on the "from_status" field.
func FromStatusHasSuffix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasSuffix(FieldFromStatus, v))
}

// FromStatusIsNil applies the IsNil predicate on the "from_status" field.
func FromStatusIsNil() predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIsNull(FieldFromStatus))
}

// FromStatusNotNil applies the NotNil predicate on the "from_status" field.
func FromStatusNotNil() predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotNull(FieldFromStatus))
}

// FromStatusEqualFold applies the EqualFold predicate on the "from_status" field.
func FromStatusEqualFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEqualFold(FieldFromStatus, v))
}

// FromStatusContainsFold applies the ContainsFold predicate on the "from_status" field.
func FromStatusContainsFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContainsFold(FieldFromStatus, v))
}

// ToStatusEQ applies the EQ predicate on the "to_status" field.
func ToStatusEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldToStatus, v))
}

// ToStatusNEQ applies the NEQ predicate on the "to_status" field.
func ToStatusNEQ(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNEQ(FieldToStatus, v))
}

// ToStatusIn applies the In predicate on the "to_status" field.
func ToStatusIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIn(FieldToStatus, vs...))
}

// ToStatusNotIn applies the NotIn predicate on the "to_status" field.
func ToStatusNotIn(vs ...string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotIn(FieldToStatus, vs...))
}

// ToStatusGT applies the GT predicate on the "to_status" field.
func ToStatusGT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGT(FieldToStatus, v))
}

// ToStatusGTE applies the GTE predicate on the "to_status" field.
func ToStatusGTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGTE(FieldToStatus, v))
}

// ToStatusLT applies the LT predicate on the "to_status" field.
func ToStatusLT(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLT(FieldToStatus, v))
}

// ToStatusLTE applies the LTE predicate on the "to_status" field.
func ToStatusLTE(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLTE(FieldToStatus, v))
}

// ToStatusContains applies the Contains predicate on the "to_status" field.
func ToStatusContains(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContains(FieldToStatus, v))
}

// ToStatusHasPrefix applies the HasPrefix predicate on the "to_status" field.
func ToStatusHasPrefix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasPrefix(FieldToStatus, v))
}

// ToStatusHasSuffix applies the HasSuffix predicate on the "to_status" field.
func ToStatusHasSuffix(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldHasSuffix(FieldToStatus, v))
}

// ToStatusIsNil applies the IsNil predicate on the "to_status" field.
func ToStatusIsNil() predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIsNull(FieldToStatus))
}

// ToStatusNotNil applies the NotNil predicate on the "to_status" field.
func ToStatusNotNil() predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotNull(FieldToStatus))
}

// ToStatusEqualFold applies the EqualFold predicate on the "to_status" field.
func ToStatusEqualFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEqualFold(FieldToStatus, v))
}

// ToStatusContainsFold applies the ContainsFold predicate on the "to_status" field.
func ToStatusContainsFold(v string) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldContainsFold(FieldToStatus, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DepositEvent {
	return predicate.DepositEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDeposit applies the HasEdge predicate on the "deposit" edge.
func HasDeposit() predicate.DepositEvent {
	return predicate.DepositEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepositTable, DepositColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepositWith applies the HasEdge predicate on the "deposit" edge with a given conditions (other predicates).
func HasDepositWith(preds ...predicate.Deposit) predicate.DepositEvent {
	return predicate.DepositEvent(func(s *sql.Selector) {
		step := newDepositStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DepositEvent) predicate.DepositEvent {
	return predicate.DepositEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DepositEvent) predicate.DepositEvent {
	return predicate.DepositEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DepositEvent) predicate.DepositEvent {
	return predicate.DepositEvent(sql.NotPredicates(p))
}
