// Code generated by ent, DO NOT EDIT.

package withdrawal

import (
	"crypto-payment-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldID, id))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldCustomerID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldIdempotencyKey, v))
}

// DestinationAddress applies equality check predicate on the "destination_address" field. It's identical to DestinationAddressEQ.
func DestinationAddress(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldDestinationAddress, v))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldTxHash, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldCurrency, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldNetwork, v))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldAsset, v))
}

// AmountAtomic applies equality check predicate on the "amount_atomic" field. It's identical to AmountAtomicEQ.
func AmountAtomic(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldAmountAtomic, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldStatus, v))
}

// Confirmations applies equality check predicate on the "confirmations" field. It's identical to ConfirmationsEQ.
func Confirmations(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldConfirmations, v))
}

// RequiredConfirmations applies equality check predicate on the "required_confirmations" field. It's identical to RequiredConfirmationsEQ.
func RequiredConfirmations(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldRequiredConfirmations, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldRetryCount, v))
}

// NextRetryAt applies equality check predicate on the "next_retry_at" field. It's identical to NextRetryAtEQ.
func NextRetryAt(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldNextRetryAt, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldFailureReason, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldUpdatedAt, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldCustomerID, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// DestinationAddressEQ applies the EQ predicate on the "destination_address" field.
func DestinationAddressEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldDestinationAddress, v))
}

// DestinationAddressNEQ applies the NEQ predicate on the "destination_address" field.
func DestinationAddressNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldDestinationAddress, v))
}

// DestinationAddressIn applies the In predicate on the "destination_address" field.
func DestinationAddressIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldDestinationAddress, vs...))
}

// DestinationAddressNotIn applies the NotIn predicate on the "destination_address" field.
func DestinationAddressNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldDestinationAddress, vs...))
}

// DestinationAddressGT applies the GT predicate on the "destination_address" field.
func DestinationAddressGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldDestinationAddress, v))
}

// DestinationAddressGTE applies the GTE predicate on the "destination_address" field.
func DestinationAddressGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldDestinationAddress, v))
}

// DestinationAddressLT applies the LT predicate on the "destination_address" field.
func DestinationAddressLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldDestinationAddress, v))
}

// DestinationAddressLTE applies the LTE predicate on the "destination_address" field.
func DestinationAddressLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldDestinationAddress, v))
}

// DestinationAddressContains applies the Contains predicate on the "destination_address" field.
func DestinationAddressContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldDestinationAddress, v))
}

// DestinationAddressHasPrefix applies the HasPrefix predicate on the "destination_address" field.
func DestinationAddressHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldDestinationAddress, v))
}

// DestinationAddressHasSuffix applies the HasSuffix predicate on the "destination_address" field.
func DestinationAddressHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldDestinationAddress, v))
}

// DestinationAddressEqualFold applies the EqualFold predicate on the "destination_address" field.
func DestinationAddressEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldDestinationAddress, v))
}

// DestinationAddressContainsFold applies the ContainsFold predicate on the "destination_address" field.
func DestinationAddressContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldDestinationAddress, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashIsNil applies the IsNil predicate on the "tx_hash" field.
func TxHashIsNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIsNull(FieldTxHash))
}

// TxHashNotNil applies the NotNil predicate on the "tx_hash" field.
func TxHashNotNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotNull(FieldTxHash))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldTxHash, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldCurrency, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldNetwork, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetIsNil applies the IsNil predicate on the "asset" field.
func AssetIsNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIsNull(FieldAsset))
}

// AssetNotNil applies the NotNil predicate on the "asset" field.
func AssetNotNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotNull(FieldAsset))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldAsset, v))
}

// AmountAtomicEQ applies the EQ predicate on the "amount_atomic" field.
func AmountAtomicEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldAmountAtomic, v))
}

// AmountAtomicNEQ applies the NEQ predicate on the "amount_atomic" field.
func AmountAtomicNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldAmountAtomic, v))
}

// AmountAtomicIn applies the In predicate on the "amount_atomic" field.
func AmountAtomicIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldAmountAtomic, vs...))
}

// AmountAtomicNotIn applies the NotIn predicate on the "amount_atomic" field.
func AmountAtomicNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldAmountAtomic, vs...))
}

// AmountAtomicGT applies the GT predicate on the "amount_atomic" field.
func AmountAtomicGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldAmountAtomic, v))
}

// AmountAtomicGTE applies the GTE predicate on the "amount_atomic" field.
func AmountAtomicGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldAmountAtomic, v))
}

// AmountAtomicLT applies the LT predicate on the "amount_atomic" field.
func AmountAtomicLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldAmountAtomic, v))
}

// AmountAtomicLTE applies the LTE predicate on the "amount_atomic" field.
func AmountAtomicLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldAmountAtomic, v))
}

// AmountAtomicContains applies the Contains predicate on the "amount_atomic" field.
func AmountAtomicContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldAmountAtomic, v))
}

// AmountAtomicHasPrefix applies the HasPrefix predicate on the "amount_atomic" field.
func AmountAtomicHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldAmountAtomic, v))
}

// AmountAtomicHasSuffix applies the HasSuffix predicate on the "amount_atomic" field.
func AmountAtomicHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldAmountAtomic, v))
}

// AmountAtomicEqualFold applies the EqualFold predicate on the "amount_atomic" field.
func AmountAtomicEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldAmountAtomic, v))
}

// AmountAtomicContainsFold applies the ContainsFold predicate on the "amount_atomic" field.
func AmountAtomicContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldAmountAtomic, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldStatus, v))
}

// ConfirmationsEQ applies the EQ predicate on the "confirmations" field.
func ConfirmationsEQ(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldConfirmations, v))
}

// ConfirmationsNEQ applies the NEQ predicate on the "confirmations" field.
func ConfirmationsNEQ(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldConfirmations, v))
}

// ConfirmationsIn applies the In predicate on the "confirmations" field.
func ConfirmationsIn(vs ...int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldConfirmations, vs...))
}

// ConfirmationsNotIn applies the NotIn predicate on the "confirmations" field.
func ConfirmationsNotIn(vs ...int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldConfirmations, vs...))
}

// ConfirmationsGT applies the GT predicate on the "confirmations" field.
func ConfirmationsGT(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldConfirmations, v))
}

// ConfirmationsGTE applies the GTE predicate on the "confirmations" field.
func ConfirmationsGTE(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldConfirmations, v))
}

// ConfirmationsLT applies the LT predicate on the "confirmations" field.
func ConfirmationsLT(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldConfirmations, v))
}

// ConfirmationsLTE applies the LTE predicate on the "confirmations" field.
func ConfirmationsLTE(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldConfirmations, v))
}

// RequiredConfirmationsEQ applies the EQ predicate on the "required_confirmations" field.
func RequiredConfirmationsEQ(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsNEQ applies the NEQ predicate on the "required_confirmations" field.
func RequiredConfirmationsNEQ(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsIn applies the In predicate on the "required_confirmations" field.
func RequiredConfirmationsIn(vs ...int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldRequiredConfirmations, vs...))
}

// RequiredConfirmationsNotIn applies the NotIn predicate on the "required_confirmations" field.
func RequiredConfirmationsNotIn(vs ...int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldRequiredConfirmations, vs...))
}

// RequiredConfirmationsGT applies the GT predicate on the "required_confirmations" field.
func RequiredConfirmationsGT(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsGTE applies the GTE predicate on the "required_confirmations" field.
func RequiredConfirmationsGTE(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsLT applies the LT predicate on the "required_confirmations" field.
func RequiredConfirmationsLT(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsLTE applies the LTE predicate on the "required_confirmations" field.
func RequiredConfirmationsLTE(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldRequiredConfirmations, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldRetryCount, v))
}

// NextRetryAtEQ applies the EQ predicate on the "next_retry_at" field.
func NextRetryAtEQ(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldNextRetryAt, v))
}

// NextRetryAtNEQ applies the NEQ predicate on the "next_retry_at" field.
func NextRetryAtNEQ(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldNextRetryAt, v))
}

// NextRetryAtIn applies the In predicate on the "next_retry_at" field.
func NextRetryAtIn(vs ...time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldNextRetryAt, vs...))
}

// NextRetryAtNotIn applies the NotIn predicate on the "next_retry_at" field.
func NextRetryAtNotIn(vs ...time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldNextRetryAt, vs...))
}

// NextRetryAtGT applies the GT predicate on the "next_retry_at" field.
func NextRetryAtGT(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldNextRetryAt, v))
}

// NextRetryAtGTE applies the GTE predicate on the "next_retry_at" field.
func NextRetryAtGTE(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldNextRetryAt, v))
}

// NextRetryAtLT applies the LT predicate on the "next_retry_at" field.
func NextRetryAtLT(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldNextRetryAt, v))
}

// NextRetryAtLTE applies the LTE predicate on the "next_retry_at" field.
func NextRetryAtLTE(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldNextRetryAt, v))
}

// NextRetryAtIsNil applies the IsNil predicate on the "next_retry_at" field.
func NextRetryAtIsNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIsNull(FieldNextRetryAt))
}

// NextRetryAtNotNil applies the NotNil predicate on the "next_retry_at" field.
func NextRetryAtNotNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotNull(FieldNextRetryAt))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldContainsFold(FieldFailureReason, v))
}

// TransactionMetadataIsNil applies the IsNil predicate on the "transaction_metadata" field.
func TransactionMetadataIsNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIsNull(FieldTransactionMetadata))
}

// TransactionMetadataNotNil applies the NotNil predicate on the "transaction_metadata" field.
func TransactionMetadataNotNil() predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotNull(FieldTransactionMetadata))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int32) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Withdrawal {
	return predicate.Withdrawal(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Withdrawal {
	return predicate.Withdrawal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Withdrawal {
	return predicate.Withdrawal(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Withdrawal {
	return predicate.Withdrawal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.WithdrawalEvent) predicate.Withdrawal {
	return predicate.Withdrawal(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Withdrawal) predicate.Withdrawal {
	return predicate.Withdrawal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Withdrawal) predicate.Withdrawal {
	return predicate.Withdrawal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Withdrawal) predicate.Withdrawal {
	return predicate.Withdrawal(sql.NotPredicates(p))
}
