// Code generated by ent, DO NOT EDIT.

package deposit

import (
	"crypto-payment-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldID, id))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCustomerID, v))
}

// AddressID applies equality check predicate on the "address_id" field. It's identical to AddressIDEQ.
func AddressID(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAddressID, v))
}

// ExternalTxID applies equality check predicate on the "external_tx_id" field. It's identical to ExternalTxIDEQ.
func ExternalTxID(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldExternalTxID, v))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldTxHash, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCurrency, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldNetwork, v))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAsset, v))
}

// AmountAtomic applies equality check predicate on the "amount_atomic" field. It's identical to AmountAtomicEQ.
func AmountAtomic(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAmountAtomic, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldStatus, v))
}

// Confirmations applies equality check predicate on the "confirmations" field. It's identical to ConfirmationsEQ.
func Confirmations(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldConfirmations, v))
}

// RequiredConfirmations applies equality check predicate on the "required_confirmations" field. It's identical to RequiredConfirmationsEQ.
func RequiredConfirmations(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldRequiredConfirmations, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldCustomerID, v))
}

// AddressIDEQ applies the EQ predicate on the "address_id" field.
func AddressIDEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAddressID, v))
}

// AddressIDNEQ applies the NEQ predicate on the "address_id" field.
func AddressIDNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAddressID, v))
}

// AddressIDIn applies the In predicate on the "address_id" field.
func AddressIDIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAddressID, vs...))
}

// AddressIDNotIn applies the NotIn predicate on the "address_id" field.
func AddressIDNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAddressID, vs...))
}

// AddressIDGT applies the GT predicate on the "address_id" field.
func AddressIDGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAddressID, v))
}

// AddressIDGTE applies the GTE predicate on the "address_id" field.
func AddressIDGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAddressID, v))
}

// AddressIDLT applies the LT predicate on the "address_id" field.
func AddressIDLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAddressID, v))
}

// AddressIDLTE applies the LTE predicate on the "address_id" field.
func AddressIDLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAddressID, v))
}

// AddressIDContains applies the Contains predicate on the "address_id" field.
func AddressIDContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAddressID, v))
}

// AddressIDHasPrefix applies the HasPrefix predicate on the "address_id" field.
func AddressIDHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAddressID, v))
}

// AddressIDHasSuffix applies the HasSuffix predicate on the "address_id" field.
func AddressIDHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAddressID, v))
}

// AddressIDEqualFold applies the EqualFold predicate on the "address_id" field.
func AddressIDEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAddressID, v))
}

// AddressIDContainsFold applies the ContainsFold predicate on the "address_id" field.
func AddressIDContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAddressID, v))
}

// ExternalTxIDEQ applies the EQ predicate on the "external_tx_id" field.
func ExternalTxIDEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldExternalTxID, v))
}

// ExternalTxIDNEQ applies the NEQ predicate on the "external_tx_id" field.
func ExternalTxIDNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldExternalTxID, v))
}

// ExternalTxIDIn applies the In predicate on the "external_tx_id" field.
func ExternalTxIDIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldExternalTxID, vs...))
}

// ExternalTxIDNotIn applies the NotIn predicate on the "external_tx_id" field.
func ExternalTxIDNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldExternalTxID, vs...))
}

// ExternalTxIDGT applies the GT predicate on the "external_tx_id" field.
func ExternalTxIDGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldExternalTxID, v))
}

// ExternalTxIDGTE applies the GTE predicate on the "external_tx_id" field.
func ExternalTxIDGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldExternalTxID, v))
}

// ExternalTxIDLT applies the LT predicate on the "external_tx_id" field.
func ExternalTxIDLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldExternalTxID, v))
}

// ExternalTxIDLTE applies the LTE predicate on the "external_tx_id" field.
func ExternalTxIDLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldExternalTxID, v))
}

// ExternalTxIDContains applies the Contains predicate on the "external_tx_id" field.
func ExternalTxIDContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldExternalTxID, v))
}

// ExternalTxIDHasPrefix applies the HasPrefix predicate on the "external_tx_id" field.
func ExternalTxIDHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldExternalTxID, v))
}

// ExternalTxIDHasSuffix applies the HasSuffix predicate on the "external_tx_id" field.
func ExternalTxIDHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldExternalTxID, v))
}

// ExternalTxIDEqualFold applies the EqualFold predicate on the "external_tx_id" field.
func ExternalTxIDEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldExternalTxID, v))
}

// ExternalTxIDContainsFold applies the ContainsFold predicate on the "external_tx_id" field.
func ExternalTxIDContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldExternalTxID, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashIsNil applies the IsNil predicate on the "tx_hash" field.
func TxHashIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldTxHash))
}

// TxHashNotNil applies the NotNil predicate on the "tx_hash" field.
func TxHashNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldTxHash))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldTxHash, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldCurrency, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldNetwork, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetIsNil applies the IsNil predicate on the "asset" field.
func AssetIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldAsset))
}

// AssetNotNil applies the NotNil predicate on the "asset" field.
func AssetNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldAsset))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAsset, v))
}

// AmountAtomicEQ applies the EQ predicate on the "amount_atomic" field.
func AmountAtomicEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAmountAtomic, v))
}

// AmountAtomicNEQ applies the NEQ predicate on the "amount_atomic" field.
func AmountAtomicNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAmountAtomic, v))
}

// AmountAtomicIn applies the In predicate on the "amount_atomic" field.
func AmountAtomicIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAmountAtomic, vs...))
}

// AmountAtomicNotIn applies the NotIn predicate on the "amount_atomic" field.
func AmountAtomicNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAmountAtomic, vs...))
}

// AmountAtomicGT applies the GT predicate on the "amount_atomic" field.
func AmountAtomicGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAmountAtomic, v))
}

// AmountAtomicGTE applies the GTE predicate on the "amount_atomic" field.
func AmountAtomicGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAmountAtomic, v))
}

// AmountAtomicLT applies the LT predicate on the "amount_atomic" field.
func AmountAtomicLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAmountAtomic, v))
}

// AmountAtomicLTE applies the LTE predicate on the "amount_atomic" field.
func AmountAtomicLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAmountAtomic, v))
}

// AmountAtomicContains applies the Contains predicate on the "amount_atomic" field.
func AmountAtomicContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAmountAtomic, v))
}

// AmountAtomicHasPrefix applies the HasPrefix predicate on the "amount_atomic" field.
func AmountAtomicHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAmountAtomic, v))
}

// AmountAtomicHasSuffix applies the HasSuffix predicate on the "amount_atomic" field.
func AmountAtomicHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAmountAtomic, v))
}

// AmountAtomicEqualFold applies the EqualFold predicate on the "amount_atomic" field.
func AmountAtomicEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAmountAtomic, v))
}

// AmountAtomicContainsFold applies the ContainsFold predicate on the "amount_atomic" field.
func AmountAtomicContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAmountAtomic, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldStatus, v))
}

// ConfirmationsEQ applies the EQ predicate on the "confirmations" field.
func ConfirmationsEQ(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldConfirmations, v))
}

// ConfirmationsNEQ applies the NEQ predicate on the "confirmations" field.
func ConfirmationsNEQ(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldConfirmations, v))
}

// ConfirmationsIn applies the In predicate on the "confirmations" field.
func ConfirmationsIn(vs ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldConfirmations, vs...))
}

// ConfirmationsNotIn applies the NotIn predicate on the "confirmations" field.
func ConfirmationsNotIn(vs ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldConfirmations, vs...))
}

// ConfirmationsGT applies the GT predicate on the "confirmations" field.
func ConfirmationsGT(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldConfirmations, v))
}

// ConfirmationsGTE applies the GTE predicate on the "confirmations" field.
func ConfirmationsGTE(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldConfirmations, v))
}

// ConfirmationsLT applies the LT predicate on the "confirmations" field.
func ConfirmationsLT(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldConfirmations, v))
}

// ConfirmationsLTE applies the LTE predicate on the "confirmations" field.
func ConfirmationsLTE(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldConfirmations, v))
}

// RequiredConfirmationsEQ applies the EQ predicate on the "required_confirmations" field.
func RequiredConfirmationsEQ(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsNEQ applies the NEQ predicate on the "required_confirmations" field.
func RequiredConfirmationsNEQ(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsIn applies the In predicate on the "required_confirmations" field.
func RequiredConfirmationsIn(vs ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldRequiredConfirmations, vs...))
}

// RequiredConfirmationsNotIn applies the NotIn predicate on the "required_confirmations" field.
func RequiredConfirmationsNotIn(vs ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldRequiredConfirmations, vs...))
}

// RequiredConfirmationsGT applies the GT predicate on the "required_confirmations" field.
func RequiredConfirmationsGT(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsGTE applies the GTE predicate on the "required_confirmations" field.
func RequiredConfirmationsGTE(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsLT applies the LT predicate on the "required_confirmations" field.
func RequiredConfirmationsLT(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldRequiredConfirmations, v))
}

// RequiredConfirmationsLTE applies the LTE predicate on the "required_confirmations" field.
func RequiredConfirmationsLTE(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldRequiredConfirmations, v))
}

// TransactionMetadataIsNil applies the IsNil predicate on the "transaction_metadata" field.
func TransactionMetadataIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldTransactionMetadata))
}

// TransactionMetadataNotNil applies the NotNil predicate on the "transaction_metadata" field.
func TransactionMetadataNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldTransactionMetadata))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int32) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAddress applies the HasEdge predicate on the "address" edge.
func HasAddress() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AddressTable, AddressColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAddressWith applies the HasEdge predicate on the "address" edge with a given conditions (other predicates).
func HasAddressWith(preds ...predicate.Address) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		step := newAddressStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.DepositEvent) predicate.Deposit {
	return predicate.Deposit(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(sql.NotPredicates(p))
}
