// Code generated by ent, DO NOT EDIT.

package hotwallet

import (
	"crypto-payment-service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContainsFold(FieldID, id))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldCurrency, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldNetwork, v))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldAsset, v))
}

// NextNonce applies equality check predicate on the "next_nonce" field. It's identical to NextNonceEQ.
func NextNonce(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldNextNonce, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContainsFold(FieldCurrency, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContainsFold(FieldNetwork, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetIsNil applies the IsNil predicate on the "asset" field.
func AssetIsNil() predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIsNull(FieldAsset))
}

// AssetNotNil applies the NotNil predicate on the "asset" field.
func AssetNotNil() predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotNull(FieldAsset))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldContainsFold(FieldAsset, v))
}

// NextNonceEQ applies the EQ predicate on the "next_nonce" field.
func NextNonceEQ(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldNextNonce, v))
}

// NextNonceNEQ applies the NEQ predicate on the "next_nonce" field.
func NextNonceNEQ(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldNextNonce, v))
}

// NextNonceIn applies the In predicate on the "next_nonce" field.
func NextNonceIn(vs ...int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldNextNonce, vs...))
}

// NextNonceNotIn applies the NotIn predicate on the "next_nonce" field.
func NextNonceNotIn(vs ...int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldNextNonce, vs...))
}

// NextNonceGT applies the GT predicate on the "next_nonce" field.
func NextNonceGT(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldNextNonce, v))
}

// NextNonceGTE applies the GTE predicate on the "next_nonce" field.
func NextNonceGTE(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldNextNonce, v))
}

// NextNonceLT applies the LT predicate on the "next_nonce" field.
func NextNonceLT(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldNextNonce, v))
}

// NextNonceLTE applies the LTE predicate on the "next_nonce" field.
func NextNonceLTE(v int64) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldNextNonce, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int32) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HotWallet {
	return predicate.HotWallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HotWallet) predicate.HotWallet {
	return predicate.HotWallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HotWallet) predicate.HotWallet {
	return predicate.HotWallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HotWallet) predicate.HotWallet {
	return predicate.HotWallet(sql.NotPredicates(p))
}
