// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/deposit"
	"crypto-payment-service/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AddressUpdate) SetCurrency(v string) *AddressUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCurrency(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *AddressUpdate) SetNetwork(v string) *AddressUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableNetwork(v *string) *AddressUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *AddressUpdate) SetAsset(v string) *AddressUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableAsset(v *string) *AddressUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// ClearAsset clears the value of the "asset" field.
func (_u *AddressUpdate) ClearAsset() *AddressUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// SetAddress sets the "address" field.
func (_u *AddressUpdate) SetAddress(v string) *AddressUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableAddress(v *string) *AddressUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// AddDepositIDs adds the "deposits" edge to the Deposit entity by IDs.
func (_u *AddressUpdate) AddDepositIDs(ids ...string) *AddressUpdate {
	_u.mutation.AddDepositIDs(ids...)
	return _u
}

// AddDeposits adds the "deposits" edges to the Deposit entity.
func (_u *AddressUpdate) AddDeposits(v ...*Deposit) *AddressUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDepositIDs(ids...)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdate) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearDeposits clears all "deposits" edges to the Deposit entity.
func (_u *AddressUpdate) ClearDeposits() *AddressUpdate {
	_u.mutation.ClearDeposits()
	return _u
}

// RemoveDepositIDs removes the "deposits" edge to Deposit entities by IDs.
func (_u *AddressUpdate) RemoveDepositIDs(ids ...string) *AddressUpdate {
	_u.mutation.RemoveDepositIDs(ids...)
	return _u
}

// RemoveDeposits removes "deposits" edges to Deposit entities.
func (_u *AddressUpdate) RemoveDeposits(v ...*Deposit) *AddressUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDepositIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := address.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Address.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := address.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Address.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := address.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Address.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := address.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Address.address": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.customer"`)
	}
	return nil
}

func (_u *AddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(address.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(address.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(address.FieldAsset, field.TypeString, value)
	}
	if _u.mutation.AssetCleared() {
		_spec.ClearField(address.FieldAsset, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(address.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDepositsIDs(); len(nodes) > 0 && !_u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepositsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetCurrency sets the "currency" field.
func (_u *AddressUpdateOne) SetCurrency(v string) *AddressUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCurrency(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *AddressUpdateOne) SetNetwork(v string) *AddressUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableNetwork(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *AddressUpdateOne) SetAsset(v string) *AddressUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableAsset(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// ClearAsset clears the value of the "asset" field.
func (_u *AddressUpdateOne) ClearAsset() *AddressUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// SetAddress sets the "address" field.
func (_u *AddressUpdateOne) SetAddress(v string) *AddressUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableAddress(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// AddDepositIDs adds the "deposits" edge to the Deposit entity by IDs.
func (_u *AddressUpdateOne) AddDepositIDs(ids ...string) *AddressUpdateOne {
	_u.mutation.AddDepositIDs(ids...)
	return _u
}

// AddDeposits adds the "deposits" edges to the Deposit entity.
func (_u *AddressUpdateOne) AddDeposits(v ...*Deposit) *AddressUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDepositIDs(ids...)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdateOne) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearDeposits clears all "deposits" edges to the Deposit entity.
func (_u *AddressUpdateOne) ClearDeposits() *AddressUpdateOne {
	_u.mutation.ClearDeposits()
	return _u
}

// RemoveDepositIDs removes the "deposits" edge to Deposit entities by IDs.
func (_u *AddressUpdateOne) RemoveDepositIDs(ids ...string) *AddressUpdateOne {
	_u.mutation.RemoveDepositIDs(ids...)
	return _u
}

// RemoveDeposits removes "deposits" edges to Deposit entities.
func (_u *AddressUpdateOne) RemoveDeposits(v ...*Deposit) *AddressUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDepositIDs(ids...)
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Address entity.
func (_u *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := address.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Address.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := address.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Address.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := address.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Address.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := address.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Address.address": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.customer"`)
	}
	return nil
}

func (_u *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(address.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(address.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(address.FieldAsset, field.TypeString, value)
	}
	if _u.mutation.AssetCleared() {
		_spec.ClearField(address.FieldAsset, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(address.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDepositsIDs(); len(nodes) > 0 && !_u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepositsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
