// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/customer"
	"crypto-payment-service/ent/deposit"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddressCreate is the builder for creating a Address entity.
type AddressCreate struct {
	config
	mutation *AddressMutation
	hooks    []Hook
}

// SetCustomerID sets the "customer_id" field.
func (_c *AddressCreate) SetCustomerID(v string) *AddressCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *AddressCreate) SetCurrency(v string) *AddressCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *AddressCreate) SetNetwork(v string) *AddressCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetAsset sets the "asset" field.
func (_c *AddressCreate) SetAsset(v string) *AddressCreate {
	_c.mutation.SetAsset(v)
	return _c
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_c *AddressCreate) SetNillableAsset(v *string) *AddressCreate {
	if v != nil {
		_c.SetAsset(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *AddressCreate) SetAddress(v string) *AddressCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AddressCreate) SetCreatedAt(v time.Time) *AddressCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AddressCreate) SetNillableCreatedAt(v *time.Time) *AddressCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AddressCreate) SetID(v string) *AddressCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AddressCreate) SetNillableID(v *string) *AddressCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_c *AddressCreate) SetCustomer(v *Customer) *AddressCreate {
	return _c.SetCustomerID(v.ID)
}

// AddDepositIDs adds the "deposits" edge to the Deposit entity by IDs.
func (_c *AddressCreate) AddDepositIDs(ids ...string) *AddressCreate {
	_c.mutation.AddDepositIDs(ids...)
	return _c
}

// AddDeposits adds the "deposits" edges to the Deposit entity.
func (_c *AddressCreate) AddDeposits(v ...*Deposit) *AddressCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDepositIDs(ids...)
}

// Mutation returns the AddressMutation object of the builder.
func (_c *AddressCreate) Mutation() *AddressMutation {
	return _c.mutation
}

// Save creates the Address in the database.
func (_c *AddressCreate) Save(ctx context.Context) (*Address, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AddressCreate) SaveX(ctx context.Context) *Address {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AddressCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := address.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := address.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AddressCreate) check() error {
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Address.customer_id"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Address.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := address.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Address.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "Address.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := address.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Address.network": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Asset(); ok {
		if err := address.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Address.asset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Address.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := address.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Address.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Address.created_at"`)}
	}
	if len(_c.mutation.CustomerIDs()) == 0 {
		return &ValidationError{Name: "customer", err: errors.New(`ent: missing required edge "Address.customer"`)}
	}
	return nil
}

func (_c *AddressCreate) sqlSave(ctx context.Context) (*Address, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Address.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AddressCreate) createSpec() (*Address, *sqlgraph.CreateSpec) {
	var (
		_node = &Address{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(address.Table, sqlgraph.NewFieldSpec(address.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(address.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(address.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.Asset(); ok {
		_spec.SetField(address.FieldAsset, field.TypeString, value)
		_node.Asset = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(address.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(address.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.CustomerTable,
			Columns: []string{address.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepositsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   address.DepositsTable,
			Columns: []string{address.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AddressCreateBulk is the builder for creating many Address entities in bulk.
type AddressCreateBulk struct {
	config
	err      error
	builders []*AddressCreate
}

// Save creates the Address entities in the database.
func (_c *AddressCreateBulk) Save(ctx context.Context) ([]*Address, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Address, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AddressCreateBulk) SaveX(ctx context.Context) []*Address {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
