// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"crypto-payment-service/ent/migrate"

	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/customer"
	"crypto-payment-service/ent/deposit"
	"crypto-payment-service/ent/depositevent"
	"crypto-payment-service/ent/hotwallet"
	"crypto-payment-service/ent/withdrawal"
	"crypto-payment-service/ent/withdrawalevent"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Address is the client for interacting with the Address builders.
	Address *AddressClient
	// Customer is the client for interacting with the Customer builders.
	Customer *CustomerClient
	// Deposit is the client for interacting with the Deposit builders.
	Deposit *DepositClient
	// DepositEvent is the client for interacting with the DepositEvent builders.
	DepositEvent *DepositEventClient
	// HotWallet is the client for interacting with the HotWallet builders.
	HotWallet *HotWalletClient
	// Withdrawal is the client for interacting with the Withdrawal builders.
	Withdrawal *WithdrawalClient
	// WithdrawalEvent is the client for interacting with the WithdrawalEvent builders.
	WithdrawalEvent *WithdrawalEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Address = NewAddressClient(c.config)
	c.Customer = NewCustomerClient(c.config)
	c.Deposit = NewDepositClient(c.config)
	c.DepositEvent = NewDepositEventClient(c.config)
	c.HotWallet = NewHotWalletClient(c.config)
	c.Withdrawal = NewWithdrawalClient(c.config)
	c.WithdrawalEvent = NewWithdrawalEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Address:         NewAddressClient(cfg),
		Customer:        NewCustomerClient(cfg),
		Deposit:         NewDepositClient(cfg),
		DepositEvent:    NewDepositEventClient(cfg),
		HotWallet:       NewHotWalletClient(cfg),
		Withdrawal:      NewWithdrawalClient(cfg),
		WithdrawalEvent: NewWithdrawalEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Address:         NewAddressClient(cfg),
		Customer:        NewCustomerClient(cfg),
		Deposit:         NewDepositClient(cfg),
		DepositEvent:    NewDepositEventClient(cfg),
		HotWallet:       NewHotWalletClient(cfg),
		Withdrawal:      NewWithdrawalClient(cfg),
		WithdrawalEvent: NewWithdrawalEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Address.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Address, c.Customer, c.Deposit, c.DepositEvent, c.HotWallet, c.Withdrawal,
		c.WithdrawalEvent,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Address, c.Customer, c.Deposit, c.DepositEvent, c.HotWallet, c.Withdrawal,
		c.WithdrawalEvent,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AddressMutation:
		return c.Address.mutate(ctx, m)
	case *CustomerMutation:
		return c.Customer.mutate(ctx, m)
	case *DepositMutation:
		return c.Deposit.mutate(ctx, m)
	case *DepositEventMutation:
		return c.DepositEvent.mutate(ctx, m)
	case *HotWalletMutation:
		return c.HotWallet.mutate(ctx, m)
	case *WithdrawalMutation:
		return c.Withdrawal.mutate(ctx, m)
	case *WithdrawalEventMutation:
		return c.WithdrawalEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AddressClient is a client for the Address schema.
type AddressClient struct {
	config
}

// NewAddressClient returns a client for the Address from the given config.
func NewAddressClient(c config) *AddressClient {
	return &AddressClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `address.Hooks(f(g(h())))`.
func (c *AddressClient) Use(hooks ...Hook) {
	c.hooks.Address = append(c.hooks.Address, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `address.Intercept(f(g(h())))`.
func (c *AddressClient) Intercept(interceptors ...Interceptor) {
	c.inters.Address = append(c.inters.Address, interceptors...)
}

// Create returns a builder for creating a Address entity.
func (c *AddressClient) Create() *AddressCreate {
	mutation := newAddressMutation(c.config, OpCreate)
	return &AddressCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Address entities.
func (c *AddressClient) CreateBulk(builders ...*AddressCreate) *AddressCreateBulk {
	return &AddressCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AddressClient) MapCreateBulk(slice any, setFunc func(*AddressCreate, int)) *AddressCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AddressCreateBulk{err: fmt.Errorf("calling to AddressClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AddressCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AddressCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Address.
func (c *AddressClient) Update() *AddressUpdate {
	mutation := newAddressMutation(c.config, OpUpdate)
	return &AddressUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AddressClient) UpdateOne(_m *Address) *AddressUpdateOne {
	mutation := newAddressMutation(c.config, OpUpdateOne, withAddress(_m))
	return &AddressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AddressClient) UpdateOneID(id string) *AddressUpdateOne {
	mutation := newAddressMutation(c.config, OpUpdateOne, withAddressID(id))
	return &AddressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Address.
func (c *AddressClient) Delete() *AddressDelete {
	mutation := newAddressMutation(c.config, OpDelete)
	return &AddressDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AddressClient) DeleteOne(_m *Address) *AddressDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AddressClient) DeleteOneID(id string) *AddressDeleteOne {
	builder := c.Delete().Where(address.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AddressDeleteOne{builder}
}

// Query returns a query builder for Address.
func (c *AddressClient) Query() *AddressQuery {
	return &AddressQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAddress},
		inters: c.Interceptors(),
	}
}

// Get returns a Address entity by its id.
func (c *AddressClient) Get(ctx context.Context, id string) (*Address, error) {
	return c.Query().Where(address.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AddressClient) GetX(ctx context.Context, id string) *Address {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomer queries the customer edge of a Address.
func (c *AddressClient) QueryCustomer(_m *Address) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(address.Table, address.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, address.CustomerTable, address.CustomerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDeposits queries the deposits edge of a Address.
func (c *AddressClient) QueryDeposits(_m *Address) *DepositQuery {
	query := (&DepositClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(address.Table, address.FieldID, id),
			sqlgraph.To(deposit.Table, deposit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, address.DepositsTable, address.DepositsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AddressClient) Hooks() []Hook {
	return c.hooks.Address
}

// Interceptors returns the client interceptors.
func (c *AddressClient) Interceptors() []Interceptor {
	return c.inters.Address
}

func (c *AddressClient) mutate(ctx context.Context, m *AddressMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AddressCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AddressUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AddressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AddressDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Address mutation op: %q", m.Op())
	}
}

// CustomerClient is a client for the Customer schema.
type CustomerClient struct {
	config
}

// NewCustomerClient returns a client for the Customer from the given config.
func NewCustomerClient(c config) *CustomerClient {
	return &CustomerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customer.Hooks(f(g(h())))`.
func (c *CustomerClient) Use(hooks ...Hook) {
	c.hooks.Customer = append(c.hooks.Customer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customer.Intercept(f(g(h())))`.
func (c *CustomerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Customer = append(c.inters.Customer, interceptors...)
}

// Create returns a builder for creating a Customer entity.
func (c *CustomerClient) Create() *CustomerCreate {
	mutation := newCustomerMutation(c.config, OpCreate)
	return &CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Customer entities.
func (c *CustomerClient) CreateBulk(builders ...*CustomerCreate) *CustomerCreateBulk {
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerClient) MapCreateBulk(slice any, setFunc func(*CustomerCreate, int)) *CustomerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerCreateBulk{err: fmt.Errorf("calling to CustomerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Customer.
func (c *CustomerClient) Update() *CustomerUpdate {
	mutation := newCustomerMutation(c.config, OpUpdate)
	return &CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerClient) UpdateOne(_m *Customer) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomer(_m))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerClient) UpdateOneID(id string) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomerID(id))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Customer.
func (c *CustomerClient) Delete() *CustomerDelete {
	mutation := newCustomerMutation(c.config, OpDelete)
	return &CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerClient) DeleteOne(_m *Customer) *CustomerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerClient) DeleteOneID(id string) *CustomerDeleteOne {
	builder := c.Delete().Where(customer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerDeleteOne{builder}
}

// Query returns a query builder for Customer.
func (c *CustomerClient) Query() *CustomerQuery {
	return &CustomerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomer},
		inters: c.Interceptors(),
	}
}

// Get returns a Customer entity by its id.
func (c *CustomerClient) Get(ctx context.Context, id string) (*Customer, error) {
	return c.Query().Where(customer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerClient) GetX(ctx context.Context, id string) *Customer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAddresses queries the addresses edge of a Customer.
func (c *CustomerClient) QueryAddresses(_m *Customer) *AddressQuery {
	query := (&AddressClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(address.Table, address.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.AddressesTable, customer.AddressesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDeposits queries the deposits edge of a Customer.
func (c *CustomerClient) QueryDeposits(_m *Customer) *DepositQuery {
	query := (&DepositClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(deposit.Table, deposit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.DepositsTable, customer.DepositsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryWithdrawals queries the withdrawals edge of a Customer.
func (c *CustomerClient) QueryWithdrawals(_m *Customer) *WithdrawalQuery {
	query := (&WithdrawalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(withdrawal.Table, withdrawal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.WithdrawalsTable, customer.WithdrawalsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CustomerClient) Hooks() []Hook {
	return c.hooks.Customer
}

// Interceptors returns the client interceptors.
func (c *CustomerClient) Interceptors() []Interceptor {
	return c.inters.Customer
}

func (c *CustomerClient) mutate(ctx context.Context, m *CustomerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Customer mutation op: %q", m.Op())
	}
}

// DepositClient is a client for the Deposit schema.
type DepositClient struct {
	config
}

// NewDepositClient returns a client for the Deposit from the given config.
func NewDepositClient(c config) *DepositClient {
	return &DepositClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deposit.Hooks(f(g(h())))`.
func (c *DepositClient) Use(hooks ...Hook) {
	c.hooks.Deposit = append(c.hooks.Deposit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deposit.Intercept(f(g(h())))`.
func (c *DepositClient) Intercept(interceptors ...Interceptor) {
	c.inters.Deposit = append(c.inters.Deposit, interceptors...)
}

// Create returns a builder for creating a Deposit entity.
func (c *DepositClient) Create() *DepositCreate {
	mutation := newDepositMutation(c.config, OpCreate)
	return &DepositCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Deposit entities.
func (c *DepositClient) CreateBulk(builders ...*DepositCreate) *DepositCreateBulk {
	return &DepositCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DepositClient) MapCreateBulk(slice any, setFunc func(*DepositCreate, int)) *DepositCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DepositCreateBulk{err: fmt.Errorf("calling to DepositClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DepositCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DepositCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Deposit.
func (c *DepositClient) Update() *DepositUpdate {
	mutation := newDepositMutation(c.config, OpUpdate)
	return &DepositUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DepositClient) UpdateOne(_m *Deposit) *DepositUpdateOne {
	mutation := newDepositMutation(c.config, OpUpdateOne, withDeposit(_m))
	return &DepositUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DepositClient) UpdateOneID(id string) *DepositUpdateOne {
	mutation := newDepositMutation(c.config, OpUpdateOne, withDepositID(id))
	return &DepositUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Deposit.
func (c *DepositClient) Delete() *DepositDelete {
	mutation := newDepositMutation(c.config, OpDelete)
	return &DepositDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DepositClient) DeleteOne(_m *Deposit) *DepositDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DepositClient) DeleteOneID(id string) *DepositDeleteOne {
	builder := c.Delete().Where(deposit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DepositDeleteOne{builder}
}

// Query returns a query builder for Deposit.
func (c *DepositClient) Query() *DepositQuery {
	return &DepositQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeposit},
		inters: c.Interceptors(),
	}
}

// Get returns a Deposit entity by its id.
func (c *DepositClient) Get(ctx context.Context, id string) (*Deposit, error) {
	return c.Query().Where(deposit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DepositClient) GetX(ctx context.Context, id string) *Deposit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomer queries the customer edge of a Deposit.
func (c *DepositClient) QueryCustomer(_m *Deposit) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deposit.Table, deposit.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deposit.CustomerTable, deposit.CustomerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAddress queries the address edge of a Deposit.
func (c *DepositClient) QueryAddress(_m *Deposit) *AddressQuery {
	query := (&AddressClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deposit.Table, deposit.FieldID, id),
			sqlgraph.To(address.Table, address.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deposit.AddressTable, deposit.AddressColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Deposit.
func (c *DepositClient) QueryEvents(_m *Deposit) *DepositEventQuery {
	query := (&DepositEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deposit.Table, deposit.FieldID, id),
			sqlgraph.To(depositevent.Table, depositevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deposit.EventsTable, deposit.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DepositClient) Hooks() []Hook {
	return c.hooks.Deposit
}

// Interceptors returns the client interceptors.
func (c *DepositClient) Interceptors() []Interceptor {
	return c.inters.Deposit
}

func (c *DepositClient) mutate(ctx context.Context, m *DepositMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DepositCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DepositUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DepositUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DepositDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Deposit mutation op: %q", m.Op())
	}
}

// DepositEventClient is a client for the DepositEvent schema.
type DepositEventClient struct {
	config
}

// NewDepositEventClient returns a client for the DepositEvent from the given config.
func NewDepositEventClient(c config) *DepositEventClient {
	return &DepositEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `depositevent.Hooks(f(g(h())))`.
func (c *DepositEventClient) Use(hooks ...Hook) {
	c.hooks.DepositEvent = append(c.hooks.DepositEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `depositevent.Intercept(f(g(h())))`.
func (c *DepositEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.DepositEvent = append(c.inters.DepositEvent, interceptors...)
}

// Create returns a builder for creating a DepositEvent entity.
func (c *DepositEventClient) Create() *DepositEventCreate {
	mutation := newDepositEventMutation(c.config, OpCreate)
	return &DepositEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DepositEvent entities.
func (c *DepositEventClient) CreateBulk(builders ...*DepositEventCreate) *DepositEventCreateBulk {
	return &DepositEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DepositEventClient) MapCreateBulk(slice any, setFunc func(*DepositEventCreate, int)) *DepositEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DepositEventCreateBulk{err: fmt.Errorf("calling to DepositEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DepositEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DepositEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DepositEvent.
func (c *DepositEventClient) Update() *DepositEventUpdate {
	mutation := newDepositEventMutation(c.config, OpUpdate)
	return &DepositEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DepositEventClient) UpdateOne(_m *DepositEvent) *DepositEventUpdateOne {
	mutation := newDepositEventMutation(c.config, OpUpdateOne, withDepositEvent(_m))
	return &DepositEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DepositEventClient) UpdateOneID(id string) *DepositEventUpdateOne {
	mutation := newDepositEventMutation(c.config, OpUpdateOne, withDepositEventID(id))
	return &DepositEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DepositEvent.
func (c *DepositEventClient) Delete() *DepositEventDelete {
	mutation := newDepositEventMutation(c.config, OpDelete)
	return &DepositEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DepositEventClient) DeleteOne(_m *DepositEvent) *DepositEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DepositEventClient) DeleteOneID(id string) *DepositEventDeleteOne {
	builder := c.Delete().Where(depositevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DepositEventDeleteOne{builder}
}

// Query returns a query builder for DepositEvent.
func (c *DepositEventClient) Query() *DepositEventQuery {
	return &DepositEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDepositEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a DepositEvent entity by its id.
func (c *DepositEventClient) Get(ctx context.Context, id string) (*DepositEvent, error) {
	return c.Query().Where(depositevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DepositEventClient) GetX(ctx context.Context, id string) *DepositEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDeposit queries the deposit edge of a DepositEvent.
func (c *DepositEventClient) QueryDeposit(_m *DepositEvent) *DepositQuery {
	query := (&DepositClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(depositevent.Table, depositevent.FieldID, id),
			sqlgraph.To(deposit.Table, deposit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, depositevent.DepositTable, depositevent.DepositColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DepositEventClient) Hooks() []Hook {
	return c.hooks.DepositEvent
}

// Interceptors returns the client interceptors.
func (c *DepositEventClient) Interceptors() []Interceptor {
	return c.inters.DepositEvent
}

func (c *DepositEventClient) mutate(ctx context.Context, m *DepositEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DepositEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DepositEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DepositEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DepositEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DepositEvent mutation op: %q", m.Op())
	}
}

// HotWalletClient is a client for the HotWallet schema.
type HotWalletClient struct {
	config
}

// NewHotWalletClient returns a client for the HotWallet from the given config.
func NewHotWalletClient(c config) *HotWalletClient {
	return &HotWalletClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `hotwallet.Hooks(f(g(h())))`.
func (c *HotWalletClient) Use(hooks ...Hook) {
	c.hooks.HotWallet = append(c.hooks.HotWallet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `hotwallet.Intercept(f(g(h())))`.
func (c *HotWalletClient) Intercept(interceptors ...Interceptor) {
	c.inters.HotWallet = append(c.inters.HotWallet, interceptors...)
}

// Create returns a builder for creating a HotWallet entity.
func (c *HotWalletClient) Create() *HotWalletCreate {
	mutation := newHotWalletMutation(c.config, OpCreate)
	return &HotWalletCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of HotWallet entities.
func (c *HotWalletClient) CreateBulk(builders ...*HotWalletCreate) *HotWalletCreateBulk {
	return &HotWalletCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *HotWalletClient) MapCreateBulk(slice any, setFunc func(*HotWalletCreate, int)) *HotWalletCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &HotWalletCreateBulk{err: fmt.Errorf("calling to HotWalletClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*HotWalletCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &HotWalletCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for HotWallet.
func (c *HotWalletClient) Update() *HotWalletUpdate {
	mutation := newHotWalletMutation(c.config, OpUpdate)
	return &HotWalletUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HotWalletClient) UpdateOne(_m *HotWallet) *HotWalletUpdateOne {
	mutation := newHotWalletMutation(c.config, OpUpdateOne, withHotWallet(_m))
	return &HotWalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HotWalletClient) UpdateOneID(id string) *HotWalletUpdateOne {
	mutation := newHotWalletMutation(c.config, OpUpdateOne, withHotWalletID(id))
	return &HotWalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for HotWallet.
func (c *HotWalletClient) Delete() *HotWalletDelete {
	mutation := newHotWalletMutation(c.config, OpDelete)
	return &HotWalletDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HotWalletClient) DeleteOne(_m *HotWallet) *HotWalletDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *HotWalletClient) DeleteOneID(id string) *HotWalletDeleteOne {
	builder := c.Delete().Where(hotwallet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HotWalletDeleteOne{builder}
}

// Query returns a query builder for HotWallet.
func (c *HotWalletClient) Query() *HotWalletQuery {
	return &HotWalletQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeHotWallet},
		inters: c.Interceptors(),
	}
}

// Get returns a HotWallet entity by its id.
func (c *HotWalletClient) Get(ctx context.Context, id string) (*HotWallet, error) {
	return c.Query().Where(hotwallet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HotWalletClient) GetX(ctx context.Context, id string) *HotWallet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *HotWalletClient) Hooks() []Hook {
	return c.hooks.HotWallet
}

// Interceptors returns the client interceptors.
func (c *HotWalletClient) Interceptors() []Interceptor {
	return c.inters.HotWallet
}

func (c *HotWalletClient) mutate(ctx context.Context, m *HotWalletMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&HotWalletCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&HotWalletUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&HotWalletUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&HotWalletDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown HotWallet mutation op: %q", m.Op())
	}
}

// WithdrawalClient is a client for the Withdrawal schema.
type WithdrawalClient struct {
	config
}

// NewWithdrawalClient returns a client for the Withdrawal from the given config.
func NewWithdrawalClient(c config) *WithdrawalClient {
	return &WithdrawalClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `withdrawal.Hooks(f(g(h())))`.
func (c *WithdrawalClient) Use(hooks ...Hook) {
	c.hooks.Withdrawal = append(c.hooks.Withdrawal, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `withdrawal.Intercept(f(g(h())))`.
func (c *WithdrawalClient) Intercept(interceptors ...Interceptor) {
	c.inters.Withdrawal = append(c.inters.Withdrawal, interceptors...)
}

// Create returns a builder for creating a Withdrawal entity.
func (c *WithdrawalClient) Create() *WithdrawalCreate {
	mutation := newWithdrawalMutation(c.config, OpCreate)
	return &WithdrawalCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Withdrawal entities.
func (c *WithdrawalClient) CreateBulk(builders ...*WithdrawalCreate) *WithdrawalCreateBulk {
	return &WithdrawalCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WithdrawalClient) MapCreateBulk(slice any, setFunc func(*WithdrawalCreate, int)) *WithdrawalCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WithdrawalCreateBulk{err: fmt.Errorf("calling to WithdrawalClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WithdrawalCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WithdrawalCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Withdrawal.
func (c *WithdrawalClient) Update() *WithdrawalUpdate {
	mutation := newWithdrawalMutation(c.config, OpUpdate)
	return &WithdrawalUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WithdrawalClient) UpdateOne(_m *Withdrawal) *WithdrawalUpdateOne {
	mutation := newWithdrawalMutation(c.config, OpUpdateOne, withWithdrawal(_m))
	return &WithdrawalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WithdrawalClient) UpdateOneID(id string) *WithdrawalUpdateOne {
	mutation := newWithdrawalMutation(c.config, OpUpdateOne, withWithdrawalID(id))
	return &WithdrawalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Withdrawal.
func (c *WithdrawalClient) Delete() *WithdrawalDelete {
	mutation := newWithdrawalMutation(c.config, OpDelete)
	return &WithdrawalDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WithdrawalClient) DeleteOne(_m *Withdrawal) *WithdrawalDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WithdrawalClient) DeleteOneID(id string) *WithdrawalDeleteOne {
	builder := c.Delete().Where(withdrawal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WithdrawalDeleteOne{builder}
}

// Query returns a query builder for Withdrawal.
func (c *WithdrawalClient) Query() *WithdrawalQuery {
	return &WithdrawalQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWithdrawal},
		inters: c.Interceptors(),
	}
}

// Get returns a Withdrawal entity by its id.
func (c *WithdrawalClient) Get(ctx context.Context, id string) (*Withdrawal, error) {
	return c.Query().Where(withdrawal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WithdrawalClient) GetX(ctx context.Context, id string) *Withdrawal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomer queries the customer edge of a Withdrawal.
func (c *WithdrawalClient) QueryCustomer(_m *Withdrawal) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(withdrawal.Table, withdrawal.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, withdrawal.CustomerTable, withdrawal.CustomerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Withdrawal.
func (c *WithdrawalClient) QueryEvents(_m *Withdrawal) *WithdrawalEventQuery {
	query := (&WithdrawalEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(withdrawal.Table, withdrawal.FieldID, id),
			sqlgraph.To(withdrawalevent.Table, withdrawalevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, withdrawal.EventsTable, withdrawal.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WithdrawalClient) Hooks() []Hook {
	return c.hooks.Withdrawal
}

// Interceptors returns the client interceptors.
func (c *WithdrawalClient) Interceptors() []Interceptor {
	return c.inters.Withdrawal
}

func (c *WithdrawalClient) mutate(ctx context.Context, m *WithdrawalMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WithdrawalCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WithdrawalUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WithdrawalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WithdrawalDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Withdrawal mutation op: %q", m.Op())
	}
}

// WithdrawalEventClient is a client for the WithdrawalEvent schema.
type WithdrawalEventClient struct {
	config
}

// NewWithdrawalEventClient returns a client for the WithdrawalEvent from the given config.
func NewWithdrawalEventClient(c config) *WithdrawalEventClient {
	return &WithdrawalEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `withdrawalevent.Hooks(f(g(h())))`.
func (c *WithdrawalEventClient) Use(hooks ...Hook) {
	c.hooks.WithdrawalEvent = append(c.hooks.WithdrawalEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `withdrawalevent.Intercept(f(g(h())))`.
func (c *WithdrawalEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.WithdrawalEvent = append(c.inters.WithdrawalEvent, interceptors...)
}

// Create returns a builder for creating a WithdrawalEvent entity.
func (c *WithdrawalEventClient) Create() *WithdrawalEventCreate {
	mutation := newWithdrawalEventMutation(c.config, OpCreate)
	return &WithdrawalEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WithdrawalEvent entities.
func (c *WithdrawalEventClient) CreateBulk(builders ...*WithdrawalEventCreate) *WithdrawalEventCreateBulk {
	return &WithdrawalEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WithdrawalEventClient) MapCreateBulk(slice any, setFunc func(*WithdrawalEventCreate, int)) *WithdrawalEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WithdrawalEventCreateBulk{err: fmt.Errorf("calling to WithdrawalEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WithdrawalEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WithdrawalEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WithdrawalEvent.
func (c *WithdrawalEventClient) Update() *WithdrawalEventUpdate {
	mutation := newWithdrawalEventMutation(c.config, OpUpdate)
	return &WithdrawalEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WithdrawalEventClient) UpdateOne(_m *WithdrawalEvent) *WithdrawalEventUpdateOne {
	mutation := newWithdrawalEventMutation(c.config, OpUpdateOne, withWithdrawalEvent(_m))
	return &WithdrawalEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WithdrawalEventClient) UpdateOneID(id string) *WithdrawalEventUpdateOne {
	mutation := newWithdrawalEventMutation(c.config, OpUpdateOne, withWithdrawalEventID(id))
	return &WithdrawalEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WithdrawalEvent.
func (c *WithdrawalEventClient) Delete() *WithdrawalEventDelete {
	mutation := newWithdrawalEventMutation(c.config, OpDelete)
	return &WithdrawalEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WithdrawalEventClient) DeleteOne(_m *WithdrawalEvent) *WithdrawalEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WithdrawalEventClient) DeleteOneID(id string) *WithdrawalEventDeleteOne {
	builder := c.Delete().Where(withdrawalevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WithdrawalEventDeleteOne{builder}
}

// Query returns a query builder for WithdrawalEvent.
func (c *WithdrawalEventClient) Query() *WithdrawalEventQuery {
	return &WithdrawalEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWithdrawalEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a WithdrawalEvent entity by its id.
func (c *WithdrawalEventClient) Get(ctx context.Context, id string) (*WithdrawalEvent, error) {
	return c.Query().Where(withdrawalevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WithdrawalEventClient) GetX(ctx context.Context, id string) *WithdrawalEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWithdrawal queries the withdrawal edge of a WithdrawalEvent.
func (c *WithdrawalEventClient) QueryWithdrawal(_m *WithdrawalEvent) *WithdrawalQuery {
	query := (&WithdrawalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(withdrawalevent.Table, withdrawalevent.FieldID, id),
			sqlgraph.To(withdrawal.Table, withdrawal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, withdrawalevent.WithdrawalTable, withdrawalevent.WithdrawalColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WithdrawalEventClient) Hooks() []Hook {
	return c.hooks.WithdrawalEvent
}

// Interceptors returns the client interceptors.
func (c *WithdrawalEventClient) Interceptors() []Interceptor {
	return c.inters.WithdrawalEvent
}

func (c *WithdrawalEventClient) mutate(ctx context.Context, m *WithdrawalEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WithdrawalEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WithdrawalEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WithdrawalEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WithdrawalEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WithdrawalEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Address, Customer, Deposit, DepositEvent, HotWallet, Withdrawal,
		WithdrawalEvent []ent.Hook
	}
	inters struct {
		Address, Customer, Deposit, DepositEvent, HotWallet, Withdrawal,
		WithdrawalEvent []ent.Interceptor
	}
)
