// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/customer"
	"crypto-payment-service/ent/deposit"
	"crypto-payment-service/ent/predicate"
	"crypto-payment-service/ent/withdrawal"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomerUpdate is the builder for updating Customer entities.
type CustomerUpdate struct {
	config
	hooks    []Hook
	mutation *CustomerMutation
}

// Where appends a list predicates to the CustomerUpdate builder.
func (_u *CustomerUpdate) Where(ps ...predicate.Customer) *CustomerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CustomerUpdate) SetExternalID(v string) *CustomerUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableExternalID(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CustomerUpdate) SetEmail(v string) *CustomerUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableEmail(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerUpdate) SetUpdatedAt(v time.Time) *CustomerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAddressIDs adds the "addresses" edge to the Address entity by IDs.
func (_u *CustomerUpdate) AddAddressIDs(ids ...string) *CustomerUpdate {
	_u.mutation.AddAddressIDs(ids...)
	return _u
}

// AddAddresses adds the "addresses" edges to the Address entity.
func (_u *CustomerUpdate) AddAddresses(v ...*Address) *CustomerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAddressIDs(ids...)
}

// AddDepositIDs adds the "deposits" edge to the Deposit entity by IDs.
func (_u *CustomerUpdate) AddDepositIDs(ids ...string) *CustomerUpdate {
	_u.mutation.AddDepositIDs(ids...)
	return _u
}

// AddDeposits adds the "deposits" edges to the Deposit entity.
func (_u *CustomerUpdate) AddDeposits(v ...*Deposit) *CustomerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDepositIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the Withdrawal entity by IDs.
func (_u *CustomerUpdate) AddWithdrawalIDs(ids ...string) *CustomerUpdate {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the Withdrawal entity.
func (_u *CustomerUpdate) AddWithdrawals(v ...*Withdrawal) *CustomerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (_u *CustomerUpdate) Mutation() *CustomerMutation {
	return _u.mutation
}

// ClearAddresses clears all "addresses" edges to the Address entity.
func (_u *CustomerUpdate) ClearAddresses() *CustomerUpdate {
	_u.mutation.ClearAddresses()
	return _u
}

// RemoveAddressIDs removes the "addresses" edge to Address entities by IDs.
func (_u *CustomerUpdate) RemoveAddressIDs(ids ...string) *CustomerUpdate {
	_u.mutation.RemoveAddressIDs(ids...)
	return _u
}

// RemoveAddresses removes "addresses" edges to Address entities.
func (_u *CustomerUpdate) RemoveAddresses(v ...*Address) *CustomerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAddressIDs(ids...)
}

// ClearDeposits clears all "deposits" edges to the Deposit entity.
func (_u *CustomerUpdate) ClearDeposits() *CustomerUpdate {
	_u.mutation.ClearDeposits()
	return _u
}

// RemoveDepositIDs removes the "deposits" edge to Deposit entities by IDs.
func (_u *CustomerUpdate) RemoveDepositIDs(ids ...string) *CustomerUpdate {
	_u.mutation.RemoveDepositIDs(ids...)
	return _u
}

// RemoveDeposits removes "deposits" edges to Deposit entities.
func (_u *CustomerUpdate) RemoveDeposits(v ...*Deposit) *CustomerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDepositIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the Withdrawal entity.
func (_u *CustomerUpdate) ClearWithdrawals() *CustomerUpdate {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to Withdrawal entities by IDs.
func (_u *CustomerUpdate) RemoveWithdrawalIDs(ids ...string) *CustomerUpdate {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to Withdrawal entities.
func (_u *CustomerUpdate) RemoveWithdrawals(v ...*Withdrawal) *CustomerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerUpdate) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := customer.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Customer.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := customer.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Customer.email": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(customer.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(customer.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AddressesTable,
			Columns: []string{customer.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAddressesIDs(); len(nodes) > 0 && !_u.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AddressesTable,
			Columns: []string{customer.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AddressesTable,
			Columns: []string{customer.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.DepositsTable,
			Columns: []string{customer.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDepositsIDs(); len(nodes) > 0 && !_u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.DepositsTable,
			Columns: []string{customer.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepositsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.DepositsTable,
			Columns: []string{customer.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.WithdrawalsTable,
			Columns: []string{customer.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.WithdrawalsTable,
			Columns: []string{customer.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.WithdrawalsTable,
			Columns: []string{customer.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomerUpdateOne is the builder for updating a single Customer entity.
type CustomerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomerMutation
}

// SetExternalID sets the "external_id" field.
func (_u *CustomerUpdateOne) SetExternalID(v string) *CustomerUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableExternalID(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CustomerUpdateOne) SetEmail(v string) *CustomerUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableEmail(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerUpdateOne) SetUpdatedAt(v time.Time) *CustomerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAddressIDs adds the "addresses" edge to the Address entity by IDs.
func (_u *CustomerUpdateOne) AddAddressIDs(ids ...string) *CustomerUpdateOne {
	_u.mutation.AddAddressIDs(ids...)
	return _u
}

// AddAddresses adds the "addresses" edges to the Address entity.
func (_u *CustomerUpdateOne) AddAddresses(v ...*Address) *CustomerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAddressIDs(ids...)
}

// AddDepositIDs adds the "deposits" edge to the Deposit entity by IDs.
func (_u *CustomerUpdateOne) AddDepositIDs(ids ...string) *CustomerUpdateOne {
	_u.mutation.AddDepositIDs(ids...)
	return _u
}

// AddDeposits adds the "deposits" edges to the Deposit entity.
func (_u *CustomerUpdateOne) AddDeposits(v ...*Deposit) *CustomerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDepositIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the Withdrawal entity by IDs.
func (_u *CustomerUpdateOne) AddWithdrawalIDs(ids ...string) *CustomerUpdateOne {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the Withdrawal entity.
func (_u *CustomerUpdateOne) AddWithdrawals(v ...*Withdrawal) *CustomerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (_u *CustomerUpdateOne) Mutation() *CustomerMutation {
	return _u.mutation
}

// ClearAddresses clears all "addresses" edges to the Address entity.
func (_u *CustomerUpdateOne) ClearAddresses() *CustomerUpdateOne {
	_u.mutation.ClearAddresses()
	return _u
}

// RemoveAddressIDs removes the "addresses" edge to Address entities by IDs.
func (_u *CustomerUpdateOne) RemoveAddressIDs(ids ...string) *CustomerUpdateOne {
	_u.mutation.RemoveAddressIDs(ids...)
	return _u
}

// RemoveAddresses removes "addresses" edges to Address entities.
func (_u *CustomerUpdateOne) RemoveAddresses(v ...*Address) *CustomerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAddressIDs(ids...)
}

// ClearDeposits clears all "deposits" edges to the Deposit entity.
func (_u *CustomerUpdateOne) ClearDeposits() *CustomerUpdateOne {
	_u.mutation.ClearDeposits()
	return _u
}

// RemoveDepositIDs removes the "deposits" edge to Deposit entities by IDs.
func (_u *CustomerUpdateOne) RemoveDepositIDs(ids ...string) *CustomerUpdateOne {
	_u.mutation.RemoveDepositIDs(ids...)
	return _u
}

// RemoveDeposits removes "deposits" edges to Deposit entities.
func (_u *CustomerUpdateOne) RemoveDeposits(v ...*Deposit) *CustomerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDepositIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the Withdrawal entity.
func (_u *CustomerUpdateOne) ClearWithdrawals() *CustomerUpdateOne {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to Withdrawal entities by IDs.
func (_u *CustomerUpdateOne) RemoveWithdrawalIDs(ids ...string) *CustomerUpdateOne {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to Withdrawal entities.
func (_u *CustomerUpdateOne) RemoveWithdrawals(v ...*Withdrawal) *CustomerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// Where appends a list predicates to the CustomerUpdate builder.
func (_u *CustomerUpdateOne) Where(ps ...predicate.Customer) *CustomerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomerUpdateOne) Select(field string, fields ...string) *CustomerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Customer entity.
func (_u *CustomerUpdateOne) Save(ctx context.Context) (*Customer, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerUpdateOne) SaveX(ctx context.Context) *Customer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := customer.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Customer.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := customer.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Customer.email": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomerUpdateOne) sqlSave(ctx context.Context) (_node *Customer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Customer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customer.FieldID)
		for _, f := range fields {
			if !customer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(customer.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(customer.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AddressesTable,
			Columns: []string{customer.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAddressesIDs(); len(nodes) > 0 && !_u.mutation.AddressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AddressesTable,
			Columns: []string{customer.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AddressesTable,
			Columns: []string{customer.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.DepositsTable,
			Columns: []string{customer.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDepositsIDs(); len(nodes) > 0 && !_u.mutation.DepositsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.DepositsTable,
			Columns: []string{customer.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepositsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.DepositsTable,
			Columns: []string{customer.DepositsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.WithdrawalsTable,
			Columns: []string{customer.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.WithdrawalsTable,
			Columns: []string{customer.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.WithdrawalsTable,
			Columns: []string{customer.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Customer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
