// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/customer"
	"crypto-payment-service/ent/deposit"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Deposit is the model entity for the Deposit schema.
type Deposit struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// AddressID holds the value of the "address_id" field.
	AddressID string `json:"address_id,omitempty"`
	// ExternalTxID holds the value of the "external_tx_id" field.
	ExternalTxID string `json:"external_tx_id,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash *string `json:"tx_hash,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// Deprecated: use currency + network
	Asset string `json:"asset,omitempty"`
	// AmountAtomic holds the value of the "amount_atomic" field.
	AmountAtomic string `json:"amount_atomic,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Confirmations holds the value of the "confirmations" field.
	Confirmations int `json:"confirmations,omitempty"`
	// RequiredConfirmations holds the value of the "required_confirmations" field.
	RequiredConfirmations int `json:"required_confirmations,omitempty"`
	// TransactionMetadata holds the value of the "transaction_metadata" field.
	TransactionMetadata map[string]interface{} `json:"transaction_metadata,omitempty"`
	// Worker identity holding the processing lease (ADR-0002)
	LockedBy *string `json:"locked_by,omitempty"`
	// Lease expiry; expired leases are reclaimable
	LockedUntil *time.Time `json:"locked_until,omitempty"`
	// Version holds the value of the "version" field.
	Version int32 `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DepositQuery when eager-loading is set.
	Edges        DepositEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DepositEdges holds the relations/edges for other nodes in the graph.
type DepositEdges struct {
	// Customer holds the value of the customer edge.
	Customer *Customer `json:"customer,omitempty"`
	// Address holds the value of the address edge.
	Address *Address `json:"address,omitempty"`
	// Events holds the value of the events edge.
	Events []*DepositEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CustomerOrErr returns the Customer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepositEdges) CustomerOrErr() (*Customer, error) {
	if e.Customer != nil {
		return e.Customer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: customer.Label}
	}
	return nil, &NotLoadedError{edge: "customer"}
}

// AddressOrErr returns the Address value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepositEdges) AddressOrErr() (*Address, error) {
	if e.Address != nil {
		return e.Address, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: address.Label}
	}
	return nil, &NotLoadedError{edge: "address"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e DepositEdges) EventsOrErr() ([]*DepositEvent, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Deposit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deposit.FieldTransactionMetadata:
			values[i] = new([]byte)
		case deposit.FieldConfirmations, deposit.FieldRequiredConfirmations, deposit.FieldVersion:
			values[i] = new(sql.NullInt64)
		case deposit.FieldID, deposit.FieldCustomerID, deposit.FieldAddressID, deposit.FieldExternalTxID, deposit.FieldTxHash, deposit.FieldCurrency, deposit.FieldNetwork, deposit.FieldAsset, deposit.FieldAmountAtomic, deposit.FieldStatus, deposit.FieldLockedBy:
			values[i] = new(sql.NullString)
		case deposit.FieldLockedUntil, deposit.FieldCreatedAt, deposit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Deposit fields.
func (_m *Deposit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deposit.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case deposit.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = value.String
			}
		case deposit.FieldAddressID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_id", values[i])
			} else if value.Valid {
				_m.AddressID = value.String
			}
		case deposit.FieldExternalTxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_tx_id", values[i])
			} else if value.Valid {
				_m.ExternalTxID = value.String
			}
		case deposit.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = new(string)
				*_m.TxHash = value.String
			}
		case deposit.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case deposit.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case deposit.FieldAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset", values[i])
			} else if value.Valid {
				_m.Asset = value.String
			}
		case deposit.FieldAmountAtomic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount_atomic", values[i])
			} else if value.Valid {
				_m.AmountAtomic = value.String
			}
		case deposit.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case deposit.FieldConfirmations:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field confirmations", values[i])
			} else if value.Valid {
				_m.Confirmations = int(value.Int64)
			}
		case deposit.FieldRequiredConfirmations:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field required_confirmations", values[i])
			} else if value.Valid {
				_m.RequiredConfirmations = int(value.Int64)
			}
		case deposit.FieldTransactionMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TransactionMetadata); err != nil {
					return fmt.Errorf("unmarshal field transaction_metadata: %w", err)
				}
			}
		case deposit.FieldLockedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locked_by", values[i])
			} else if value.Valid {
				_m.LockedBy = new(string)
				*_m.LockedBy = value.String
			}
		case deposit.FieldLockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_until", values[i])
			} else if value.Valid {
				_m.LockedUntil = new(time.Time)
				*_m.LockedUntil = value.Time
			}
		case deposit.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int32(value.Int64)
			}
		case deposit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deposit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Deposit.
// This includes values selected through modifiers, order, etc.
func (_m *Deposit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCustomer queries the "customer" edge of the Deposit entity.
func (_m *Deposit) QueryCustomer() *CustomerQuery {
	return NewDepositClient(_m.config).QueryCustomer(_m)
}

// QueryAddress queries the "address" edge of the Deposit entity.
func (_m *Deposit) QueryAddress() *AddressQuery {
	return NewDepositClient(_m.config).QueryAddress(_m)
}

// QueryEvents queries the "events" edge of the Deposit entity.
func (_m *Deposit) QueryEvents() *DepositEventQuery {
	return NewDepositClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Deposit.
// Note that you need to call Deposit.Unwrap() before calling this method if this Deposit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Deposit) Update() *DepositUpdateOne {
	return NewDepositClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Deposit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Deposit) Unwrap() *Deposit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Deposit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Deposit) String() string {
	var builder strings.Builder
	builder.WriteString("Deposit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("customer_id=")
	builder.WriteString(_m.CustomerID)
	builder.WriteString(", ")
	builder.WriteString("address_id=")
	builder.WriteString(_m.AddressID)
	builder.WriteString(", ")
	builder.WriteString("external_tx_id=")
	builder.WriteString(_m.ExternalTxID)
	builder.WriteString(", ")
	if v := _m.TxHash; v != nil {
		builder.WriteString("tx_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("asset=")
	builder.WriteString(_m.Asset)
	builder.WriteString(", ")
	builder.WriteString("amount_atomic=")
	builder.WriteString(_m.AmountAtomic)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("confirmations=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confirmations))
	builder.WriteString(", ")
	builder.WriteString("required_confirmations=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiredConfirmations))
	builder.WriteString(", ")
	builder.WriteString("transaction_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransactionMetadata))
	builder.WriteString(", ")
	if v := _m.LockedBy; v != nil {
		builder.WriteString("locked_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LockedUntil; v != nil {
		builder.WriteString("locked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Deposits is a parsable slice of Deposit.
type Deposits []*Deposit
