// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/deposit"
	"crypto-payment-service/ent/depositevent"
	"crypto-payment-service/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepositUpdate is the builder for updating Deposit entities.
type DepositUpdate struct {
	config
	hooks    []Hook
	mutation *DepositMutation
}

// Where appends a list predicates to the DepositUpdate builder.
func (_u *DepositUpdate) Where(ps ...predicate.Deposit) *DepositUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAddressID sets the "address_id" field.
func (_u *DepositUpdate) SetAddressID(v string) *DepositUpdate {
	_u.mutation.SetAddressID(v)
	return _u
}

// SetNillableAddressID sets the "address_id" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAddressID(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAddressID(*v)
	}
	return _u
}

// SetExternalTxID sets the "external_tx_id" field.
func (_u *DepositUpdate) SetExternalTxID(v string) *DepositUpdate {
	_u.mutation.SetExternalTxID(v)
	return _u
}

// SetNillableExternalTxID sets the "external_tx_id" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableExternalTxID(v *string) *DepositUpdate {
	if v != nil {
		_u.SetExternalTxID(*v)
	}
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *DepositUpdate) SetTxHash(v string) *DepositUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableTxHash(v *string) *DepositUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *DepositUpdate) ClearTxHash() *DepositUpdate {
	_u.mutation.ClearTxHash()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *DepositUpdate) SetCurrency(v string) *DepositUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableCurrency(v *string) *DepositUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *DepositUpdate) SetNetwork(v string) *DepositUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableNetwork(v *string) *DepositUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *DepositUpdate) SetAsset(v string) *DepositUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAsset(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// ClearAsset clears the value of the "asset" field.
func (_u *DepositUpdate) ClearAsset() *DepositUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// SetAmountAtomic sets the "amount_atomic" field.
func (_u *DepositUpdate) SetAmountAtomic(v string) *DepositUpdate {
	_u.mutation.SetAmountAtomic(v)
	return _u
}

// SetNillableAmountAtomic sets the "amount_atomic" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAmountAtomic(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAmountAtomic(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DepositUpdate) SetStatus(v string) *DepositUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableStatus(v *string) *DepositUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfirmations sets the "confirmations" field.
func (_u *DepositUpdate) SetConfirmations(v int) *DepositUpdate {
	_u.mutation.ResetConfirmations()
	_u.mutation.SetConfirmations(v)
	return _u
}

// SetNillableConfirmations sets the "confirmations" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableConfirmations(v *int) *DepositUpdate {
	if v != nil {
		_u.SetConfirmations(*v)
	}
	return _u
}

// AddConfirmations adds value to the "confirmations" field.
func (_u *DepositUpdate) AddConfirmations(v int) *DepositUpdate {
	_u.mutation.AddConfirmations(v)
	return _u
}

// SetRequiredConfirmations sets the "required_confirmations" field.
func (_u *DepositUpdate) SetRequiredConfirmations(v int) *DepositUpdate {
	_u.mutation.ResetRequiredConfirmations()
	_u.mutation.SetRequiredConfirmations(v)
	return _u
}

// SetNillableRequiredConfirmations sets the "required_confirmations" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableRequiredConfirmations(v *int) *DepositUpdate {
	if v != nil {
		_u.SetRequiredConfirmations(*v)
	}
	return _u
}

// AddRequiredConfirmations adds value to the "required_confirmations" field.
func (_u *DepositUpdate) AddRequiredConfirmations(v int) *DepositUpdate {
	_u.mutation.AddRequiredConfirmations(v)
	return _u
}

// SetTransactionMetadata sets the "transaction_metadata" field.
func (_u *DepositUpdate) SetTransactionMetadata(v map[string]interface{}) *DepositUpdate {
	_u.mutation.SetTransactionMetadata(v)
	return _u
}

// ClearTransactionMetadata clears the value of the "transaction_metadata" field.
func (_u *DepositUpdate) ClearTransactionMetadata() *DepositUpdate {
	_u.mutation.ClearTransactionMetadata()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *DepositUpdate) SetLockedBy(v string) *DepositUpdate {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableLockedBy(v *string) *DepositUpdate {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *DepositUpdate) ClearLockedBy() *DepositUpdate {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *DepositUpdate) SetLockedUntil(v time.Time) *DepositUpdate {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableLockedUntil(v *time.Time) *DepositUpdate {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *DepositUpdate) ClearLockedUntil() *DepositUpdate {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetVersion sets the "version" field.
func (_u *DepositUpdate) SetVersion(v int32) *DepositUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableVersion(v *int32) *DepositUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *DepositUpdate) AddVersion(v int32) *DepositUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepositUpdate) SetUpdatedAt(v time.Time) *DepositUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAddress sets the "address" edge to the Address entity.
func (_u *DepositUpdate) SetAddress(v *Address) *DepositUpdate {
	return _u.SetAddressID(v.ID)
}

// AddEventIDs adds the "events" edge to the DepositEvent entity by IDs.
func (_u *DepositUpdate) AddEventIDs(ids ...string) *DepositUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the DepositEvent entity.
func (_u *DepositUpdate) AddEvents(v ...*DepositEvent) *DepositUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the DepositMutation object of the builder.
func (_u *DepositUpdate) Mutation() *DepositMutation {
	return _u.mutation
}

// ClearAddress clears the "address" edge to the Address entity.
func (_u *DepositUpdate) ClearAddress() *DepositUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// ClearEvents clears all "events" edges to the DepositEvent entity.
func (_u *DepositUpdate) ClearEvents() *DepositUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to DepositEvent entities by IDs.
func (_u *DepositUpdate) RemoveEventIDs(ids ...string) *DepositUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to DepositEvent entities.
func (_u *DepositUpdate) RemoveEvents(v ...*DepositEvent) *DepositUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepositUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepositUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepositUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepositUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepositUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepositUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := deposit.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Deposit.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := deposit.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Deposit.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := deposit.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Deposit.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Deposit.status": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deposit.customer"`)
	}
	if _u.mutation.AddressCleared() && len(_u.mutation.AddressIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deposit.address"`)
	}
	return nil
}

func (_u *DepositUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deposit.Table, deposit.Columns, sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalTxID(); ok {
		_spec.SetField(deposit.FieldExternalTxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(deposit.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(deposit.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(deposit.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(deposit.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(deposit.FieldAsset, field.TypeString, value)
	}
	if _u.mutation.AssetCleared() {
		_spec.ClearField(deposit.FieldAsset, field.TypeString)
	}
	if value, ok := _u.mutation.AmountAtomic(); ok {
		_spec.SetField(deposit.FieldAmountAtomic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmations(); ok {
		_spec.SetField(deposit.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfirmations(); ok {
		_spec.AddField(deposit.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequiredConfirmations(); ok {
		_spec.SetField(deposit.FieldRequiredConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequiredConfirmations(); ok {
		_spec.AddField(deposit.FieldRequiredConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TransactionMetadata(); ok {
		_spec.SetField(deposit.FieldTransactionMetadata, field.TypeJSON, value)
	}
	if _u.mutation.TransactionMetadataCleared() {
		_spec.ClearField(deposit.FieldTransactionMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(deposit.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(deposit.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(deposit.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(deposit.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(deposit.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(deposit.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deposit.AddressTable,
			Columns: []string{deposit.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deposit.AddressTable,
			Columns: []string{deposit.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deposit.EventsTable,
			Columns: []string{deposit.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deposit.EventsTable,
			Columns: []string{deposit.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deposit.EventsTable,
			Columns: []string{deposit.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepositUpdateOne is the builder for updating a single Deposit entity.
type DepositUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepositMutation
}

// SetAddressID sets the "address_id" field.
func (_u *DepositUpdateOne) SetAddressID(v string) *DepositUpdateOne {
	_u.mutation.SetAddressID(v)
	return _u
}

// SetNillableAddressID sets the "address_id" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAddressID(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAddressID(*v)
	}
	return _u
}

// SetExternalTxID sets the "external_tx_id" field.
func (_u *DepositUpdateOne) SetExternalTxID(v string) *DepositUpdateOne {
	_u.mutation.SetExternalTxID(v)
	return _u
}

// SetNillableExternalTxID sets the "external_tx_id" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableExternalTxID(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetExternalTxID(*v)
	}
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *DepositUpdateOne) SetTxHash(v string) *DepositUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableTxHash(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *DepositUpdateOne) ClearTxHash() *DepositUpdateOne {
	_u.mutation.ClearTxHash()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *DepositUpdateOne) SetCurrency(v string) *DepositUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableCurrency(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *DepositUpdateOne) SetNetwork(v string) *DepositUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableNetwork(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *DepositUpdateOne) SetAsset(v string) *DepositUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAsset(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// ClearAsset clears the value of the "asset" field.
func (_u *DepositUpdateOne) ClearAsset() *DepositUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// SetAmountAtomic sets the "amount_atomic" field.
func (_u *DepositUpdateOne) SetAmountAtomic(v string) *DepositUpdateOne {
	_u.mutation.SetAmountAtomic(v)
	return _u
}

// SetNillableAmountAtomic sets the "amount_atomic" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAmountAtomic(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAmountAtomic(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DepositUpdateOne) SetStatus(v string) *DepositUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableStatus(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfirmations sets the "confirmations" field.
func (_u *DepositUpdateOne) SetConfirmations(v int) *DepositUpdateOne {
	_u.mutation.ResetConfirmations()
	_u.mutation.SetConfirmations(v)
	return _u
}

// SetNillableConfirmations sets the "confirmations" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableConfirmations(v *int) *DepositUpdateOne {
	if v != nil {
		_u.SetConfirmations(*v)
	}
	return _u
}

// AddConfirmations adds value to the "confirmations" field.
func (_u *DepositUpdateOne) AddConfirmations(v int) *DepositUpdateOne {
	_u.mutation.AddConfirmations(v)
	return _u
}

// SetRequiredConfirmations sets the "required_confirmations" field.
func (_u *DepositUpdateOne) SetRequiredConfirmations(v int) *DepositUpdateOne {
	_u.mutation.ResetRequiredConfirmations()
	_u.mutation.SetRequiredConfirmations(v)
	return _u
}

// SetNillableRequiredConfirmations sets the "required_confirmations" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableRequiredConfirmations(v *int) *DepositUpdateOne {
	if v != nil {
		_u.SetRequiredConfirmations(*v)
	}
	return _u
}

// AddRequiredConfirmations adds value to the "required_confirmations" field.
func (_u *DepositUpdateOne) AddRequiredConfirmations(v int) *DepositUpdateOne {
	_u.mutation.AddRequiredConfirmations(v)
	return _u
}

// SetTransactionMetadata sets the "transaction_metadata" field.
func (_u *DepositUpdateOne) SetTransactionMetadata(v map[string]interface{}) *DepositUpdateOne {
	_u.mutation.SetTransactionMetadata(v)
	return _u
}

// ClearTransactionMetadata clears the value of the "transaction_metadata" field.
func (_u *DepositUpdateOne) ClearTransactionMetadata() *DepositUpdateOne {
	_u.mutation.ClearTransactionMetadata()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *DepositUpdateOne) SetLockedBy(v string) *DepositUpdateOne {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableLockedBy(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *DepositUpdateOne) ClearLockedBy() *DepositUpdateOne {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *DepositUpdateOne) SetLockedUntil(v time.Time) *DepositUpdateOne {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableLockedUntil(v *time.Time) *DepositUpdateOne {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *DepositUpdateOne) ClearLockedUntil() *DepositUpdateOne {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetVersion sets the "version" field.
func (_u *DepositUpdateOne) SetVersion(v int32) *DepositUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableVersion(v *int32) *DepositUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *DepositUpdateOne) AddVersion(v int32) *DepositUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepositUpdateOne) SetUpdatedAt(v time.Time) *DepositUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAddress sets the "address" edge to the Address entity.
func (_u *DepositUpdateOne) SetAddress(v *Address) *DepositUpdateOne {
	return _u.SetAddressID(v.ID)
}

// AddEventIDs adds the "events" edge to the DepositEvent entity by IDs.
func (_u *DepositUpdateOne) AddEventIDs(ids ...string) *DepositUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the DepositEvent entity.
func (_u *DepositUpdateOne) AddEvents(v ...*DepositEvent) *DepositUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the DepositMutation object of the builder.
func (_u *DepositUpdateOne) Mutation() *DepositMutation {
	return _u.mutation
}

// ClearAddress clears the "address" edge to the Address entity.
func (_u *DepositUpdateOne) ClearAddress() *DepositUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// ClearEvents clears all "events" edges to the DepositEvent entity.
func (_u *DepositUpdateOne) ClearEvents() *DepositUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to DepositEvent entities by IDs.
func (_u *DepositUpdateOne) RemoveEventIDs(ids ...string) *DepositUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to DepositEvent entities.
func (_u *DepositUpdateOne) RemoveEvents(v ...*DepositEvent) *DepositUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the DepositUpdate builder.
func (_u *DepositUpdateOne) Where(ps ...predicate.Deposit) *DepositUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepositUpdateOne) Select(field string, fields ...string) *DepositUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deposit entity.
func (_u *DepositUpdateOne) Save(ctx context.Context) (*Deposit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepositUpdateOne) SaveX(ctx context.Context) *Deposit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepositUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepositUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepositUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepositUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := deposit.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Deposit.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := deposit.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Deposit.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := deposit.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Deposit.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Deposit.status": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deposit.customer"`)
	}
	if _u.mutation.AddressCleared() && len(_u.mutation.AddressIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deposit.address"`)
	}
	return nil
}

func (_u *DepositUpdateOne) sqlSave(ctx context.Context) (_node *Deposit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deposit.Table, deposit.Columns, sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deposit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deposit.FieldID)
		for _, f := range fields {
			if !deposit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalTxID(); ok {
		_spec.SetField(deposit.FieldExternalTxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(deposit.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(deposit.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(deposit.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(deposit.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(deposit.FieldAsset, field.TypeString, value)
	}
	if _u.mutation.AssetCleared() {
		_spec.ClearField(deposit.FieldAsset, field.TypeString)
	}
	if value, ok := _u.mutation.AmountAtomic(); ok {
		_spec.SetField(deposit.FieldAmountAtomic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmations(); ok {
		_spec.SetField(deposit.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfirmations(); ok {
		_spec.AddField(deposit.FieldConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequiredConfirmations(); ok {
		_spec.SetField(deposit.FieldRequiredConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequiredConfirmations(); ok {
		_spec.AddField(deposit.FieldRequiredConfirmations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TransactionMetadata(); ok {
		_spec.SetField(deposit.FieldTransactionMetadata, field.TypeJSON, value)
	}
	if _u.mutation.TransactionMetadataCleared() {
		_spec.ClearField(deposit.FieldTransactionMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(deposit.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(deposit.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(deposit.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(deposit.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(deposit.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(deposit.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deposit.AddressTable,
			Columns: []string{deposit.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deposit.AddressTable,
			Columns: []string{deposit.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deposit.EventsTable,
			Columns: []string{deposit.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deposit.EventsTable,
			Columns: []string{deposit.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deposit.EventsTable,
			Columns: []string{deposit.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deposit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
