// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crypto-payment-service/ent/deposit"
	"crypto-payment-service/ent/depositevent"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DepositEvent is the model entity for the DepositEvent schema.
type DepositEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// DepositID holds the value of the "deposit_id" field.
	DepositID string `json:"deposit_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// FromStatus holds the value of the "from_status" field.
	FromStatus *string `json:"from_status,omitempty"`
	// ToStatus holds the value of the "to_status" field.
	ToStatus *string `json:"to_status,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DepositEventQuery when eager-loading is set.
	Edges        DepositEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DepositEventEdges holds the relations/edges for other nodes in the graph.
type DepositEventEdges struct {
	// Deposit holds the value of the deposit edge.
	Deposit *Deposit `json:"deposit,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DepositOrErr returns the Deposit value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepositEventEdges) DepositOrErr() (*Deposit, error) {
	if e.Deposit != nil {
		return e.Deposit, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: deposit.Label}
	}
	return nil, &NotLoadedError{edge: "deposit"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DepositEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case depositevent.FieldMetadata:
			values[i] = new([]byte)
		case depositevent.FieldID, depositevent.FieldDepositID, depositevent.FieldEventType, depositevent.FieldFromStatus, depositevent.FieldToStatus:
			values[i] = new(sql.NullString)
		case depositevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DepositEvent fields.
func (_m *DepositEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case depositevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case depositevent.FieldDepositID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deposit_id", values[i])
			} else if value.Valid {
				_m.DepositID = value.String
			}
		case depositevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case depositevent.FieldFromStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_status", values[i])
			} else if value.Valid {
				_m.FromStatus = new(string)
				*_m.FromStatus = value.String
			}
		case depositevent.FieldToStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_status", values[i])
			} else if value.Valid {
				_m.ToStatus = new(string)
				*_m.ToStatus = value.String
			}
		case depositevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case depositevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DepositEvent.
// This includes values selected through modifiers, order, etc.
func (_m *DepositEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDeposit queries the "deposit" edge of the DepositEvent entity.
func (_m *DepositEvent) QueryDeposit() *DepositQuery {
	return NewDepositEventClient(_m.config).QueryDeposit(_m)
}

// Update returns a builder for updating this DepositEvent.
// Note that you need to call DepositEvent.Unwrap() before calling this method if this DepositEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DepositEvent) Update() *DepositEventUpdateOne {
	return NewDepositEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DepositEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DepositEvent) Unwrap() *DepositEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DepositEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DepositEvent) String() string {
	var builder strings.Builder
	builder.WriteString("DepositEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("deposit_id=")
	builder.WriteString(_m.DepositID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	if v := _m.FromStatus; v != nil {
		builder.WriteString("from_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ToStatus; v != nil {
		builder.WriteString("to_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DepositEvents is a parsable slice of DepositEvent.
type DepositEvents []*DepositEvent
