// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/hotwallet"
	"crypto-payment-service/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HotWalletUpdate is the builder for updating HotWallet entities.
type HotWalletUpdate struct {
	config
	hooks    []Hook
	mutation *HotWalletMutation
}

// Where appends a list predicates to the HotWalletUpdate builder.
func (_u *HotWalletUpdate) Where(ps ...predicate.HotWallet) *HotWalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *HotWalletUpdate) SetCurrency(v string) *HotWalletUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *HotWalletUpdate) SetNillableCurrency(v *string) *HotWalletUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *HotWalletUpdate) SetNetwork(v string) *HotWalletUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *HotWalletUpdate) SetNillableNetwork(v *string) *HotWalletUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *HotWalletUpdate) SetAsset(v string) *HotWalletUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *HotWalletUpdate) SetNillableAsset(v *string) *HotWalletUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// ClearAsset clears the value of the "asset" field.
func (_u *HotWalletUpdate) ClearAsset() *HotWalletUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// SetNextNonce sets the "next_nonce" field.
func (_u *HotWalletUpdate) SetNextNonce(v int64) *HotWalletUpdate {
	_u.mutation.ResetNextNonce()
	_u.mutation.SetNextNonce(v)
	return _u
}

// SetNillableNextNonce sets the "next_nonce" field if the given value is not nil.
func (_u *HotWalletUpdate) SetNillableNextNonce(v *int64) *HotWalletUpdate {
	if v != nil {
		_u.SetNextNonce(*v)
	}
	return _u
}

// AddNextNonce adds value to the "next_nonce" field.
func (_u *HotWalletUpdate) AddNextNonce(v int64) *HotWalletUpdate {
	_u.mutation.AddNextNonce(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *HotWalletUpdate) SetVersion(v int32) *HotWalletUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *HotWalletUpdate) SetNillableVersion(v *int32) *HotWalletUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *HotWalletUpdate) AddVersion(v int32) *HotWalletUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HotWalletUpdate) SetUpdatedAt(v time.Time) *HotWalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HotWalletMutation object of the builder.
func (_u *HotWalletUpdate) Mutation() *HotWalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HotWalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotWalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HotWalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotWalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HotWalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hotwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotWalletUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := hotwallet.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "HotWallet.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := hotwallet.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "HotWallet.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := hotwallet.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "HotWallet.asset": %w`, err)}
		}
	}
	return nil
}

func (_u *HotWalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hotwallet.Table, hotwallet.Columns, sqlgraph.NewFieldSpec(hotwallet.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(hotwallet.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(hotwallet.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(hotwallet.FieldAsset, field.TypeString, value)
	}
	if _u.mutation.AssetCleared() {
		_spec.ClearField(hotwallet.FieldAsset, field.TypeString)
	}
	if value, ok := _u.mutation.NextNonce(); ok {
		_spec.SetField(hotwallet.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextNonce(); ok {
		_spec.AddField(hotwallet.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(hotwallet.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(hotwallet.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hotwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HotWalletUpdateOne is the builder for updating a single HotWallet entity.
type HotWalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HotWalletMutation
}

// SetCurrency sets the "currency" field.
func (_u *HotWalletUpdateOne) SetCurrency(v string) *HotWalletUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *HotWalletUpdateOne) SetNillableCurrency(v *string) *HotWalletUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *HotWalletUpdateOne) SetNetwork(v string) *HotWalletUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *HotWalletUpdateOne) SetNillableNetwork(v *string) *HotWalletUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *HotWalletUpdateOne) SetAsset(v string) *HotWalletUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *HotWalletUpdateOne) SetNillableAsset(v *string) *HotWalletUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// ClearAsset clears the value of the "asset" field.
func (_u *HotWalletUpdateOne) ClearAsset() *HotWalletUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// SetNextNonce sets the "next_nonce" field.
func (_u *HotWalletUpdateOne) SetNextNonce(v int64) *HotWalletUpdateOne {
	_u.mutation.ResetNextNonce()
	_u.mutation.SetNextNonce(v)
	return _u
}

// SetNillableNextNonce sets the "next_nonce" field if the given value is not nil.
func (_u *HotWalletUpdateOne) SetNillableNextNonce(v *int64) *HotWalletUpdateOne {
	if v != nil {
		_u.SetNextNonce(*v)
	}
	return _u
}

// AddNextNonce adds value to the "next_nonce" field.
func (_u *HotWalletUpdateOne) AddNextNonce(v int64) *HotWalletUpdateOne {
	_u.mutation.AddNextNonce(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *HotWalletUpdateOne) SetVersion(v int32) *HotWalletUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *HotWalletUpdateOne) SetNillableVersion(v *int32) *HotWalletUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *HotWalletUpdateOne) AddVersion(v int32) *HotWalletUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HotWalletUpdateOne) SetUpdatedAt(v time.Time) *HotWalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HotWalletMutation object of the builder.
func (_u *HotWalletUpdateOne) Mutation() *HotWalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the HotWalletUpdate builder.
func (_u *HotWalletUpdateOne) Where(ps ...predicate.HotWallet) *HotWalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HotWalletUpdateOne) Select(field string, fields ...string) *HotWalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HotWallet entity.
func (_u *HotWalletUpdateOne) Save(ctx context.Context) (*HotWallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotWalletUpdateOne) SaveX(ctx context.Context) *HotWallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HotWalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotWalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HotWalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := hotwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotWalletUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := hotwallet.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "HotWallet.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := hotwallet.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "HotWallet.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := hotwallet.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "HotWallet.asset": %w`, err)}
		}
	}
	return nil
}

func (_u *HotWalletUpdateOne) sqlSave(ctx context.Context) (_node *HotWallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hotwallet.Table, hotwallet.Columns, sqlgraph.NewFieldSpec(hotwallet.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HotWallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hotwallet.FieldID)
		for _, f := range fields {
			if !hotwallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hotwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(hotwallet.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(hotwallet.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(hotwallet.FieldAsset, field.TypeString, value)
	}
	if _u.mutation.AssetCleared() {
		_spec.ClearField(hotwallet.FieldAsset, field.TypeString)
	}
	if value, ok := _u.mutation.NextNonce(); ok {
		_spec.SetField(hotwallet.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextNonce(); ok {
		_spec.AddField(hotwallet.FieldNextNonce, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(hotwallet.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(hotwallet.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hotwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &HotWallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
