// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crypto-payment-service/ent/hotwallet"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// HotWallet is the model entity for the HotWallet schema.
type HotWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// Deprecated: use currency + network
	Asset string `json:"asset,omitempty"`
	// NextNonce holds the value of the "next_nonce" field.
	NextNonce int64 `json:"next_nonce,omitempty"`
	// Version holds the value of the "version" field.
	Version int32 `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HotWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hotwallet.FieldNextNonce, hotwallet.FieldVersion:
			values[i] = new(sql.NullInt64)
		case hotwallet.FieldID, hotwallet.FieldCurrency, hotwallet.FieldNetwork, hotwallet.FieldAsset:
			values[i] = new(sql.NullString)
		case hotwallet.FieldCreatedAt, hotwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HotWallet fields.
func (_m *HotWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hotwallet.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case hotwallet.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case hotwallet.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case hotwallet.FieldAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset", values[i])
			} else if value.Valid {
				_m.Asset = value.String
			}
		case hotwallet.FieldNextNonce:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_nonce", values[i])
			} else if value.Valid {
				_m.NextNonce = value.Int64
			}
		case hotwallet.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int32(value.Int64)
			}
		case hotwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case hotwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HotWallet.
// This includes values selected through modifiers, order, etc.
func (_m *HotWallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HotWallet.
// Note that you need to call HotWallet.Unwrap() before calling this method if this HotWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HotWallet) Update() *HotWalletUpdateOne {
	return NewHotWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HotWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HotWallet) Unwrap() *HotWallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HotWallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HotWallet) String() string {
	var builder strings.Builder
	builder.WriteString("HotWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("asset=")
	builder.WriteString(_m.Asset)
	builder.WriteString(", ")
	builder.WriteString("next_nonce=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextNonce))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// HotWallets is a parsable slice of HotWallet.
type HotWallets []*HotWallet
