// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crypto-payment-service/ent/address"
	"crypto-payment-service/ent/customer"
	"crypto-payment-service/ent/deposit"
	"crypto-payment-service/ent/depositevent"
	"crypto-payment-service/ent/hotwallet"
	"crypto-payment-service/ent/schema"
	"crypto-payment-service/ent/withdrawal"
	"crypto-payment-service/ent/withdrawalevent"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressFields := schema.Address{}.Fields()
	_ = addressFields
	// addressDescCurrency is the schema descriptor for currency field.
	addressDescCurrency := addressFields[2].Descriptor()
	// address.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	address.CurrencyValidator = addressDescCurrency.Validators[0].(func(string) error)
	// addressDescNetwork is the schema descriptor for network field.
	addressDescNetwork := addressFields[3].Descriptor()
	// address.NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	address.NetworkValidator = addressDescNetwork.Validators[0].(func(string) error)
	// addressDescAsset is the schema descriptor for asset field.
	addressDescAsset := addressFields[4].Descriptor()
	// address.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	address.AssetValidator = addressDescAsset.Validators[0].(func(string) error)
	// addressDescAddress is the schema descriptor for address field.
	addressDescAddress := addressFields[5].Descriptor()
	// address.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	address.AddressValidator = addressDescAddress.Validators[0].(func(string) error)
	// addressDescCreatedAt is the schema descriptor for created_at field.
	addressDescCreatedAt := addressFields[6].Descriptor()
	// address.DefaultCreatedAt holds the default value on creation for the created_at field.
	address.DefaultCreatedAt = addressDescCreatedAt.Default.(func() time.Time)
	// addressDescID is the schema descriptor for id field.
	addressDescID := addressFields[0].Descriptor()
	// address.DefaultID holds the default value on creation for the id field.
	address.DefaultID = addressDescID.Default.(func() string)
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescExternalID is the schema descriptor for external_id field.
	customerDescExternalID := customerFields[1].Descriptor()
	// customer.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	customer.ExternalIDValidator = customerDescExternalID.Validators[0].(func(string) error)
	// customerDescEmail is the schema descriptor for email field.
	customerDescEmail := customerFields[2].Descriptor()
	// customer.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	customer.EmailValidator = customerDescEmail.Validators[0].(func(string) error)
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[3].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
	// customerDescUpdatedAt is the schema descriptor for updated_at field.
	customerDescUpdatedAt := customerFields[4].Descriptor()
	// customer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	customer.DefaultUpdatedAt = customerDescUpdatedAt.Default.(func() time.Time)
	// customer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	customer.UpdateDefaultUpdatedAt = customerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() string)
	depositFields := schema.Deposit{}.Fields()
	_ = depositFields
	// depositDescCurrency is the schema descriptor for currency field.
	depositDescCurrency := depositFields[5].Descriptor()
	// deposit.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	deposit.CurrencyValidator = depositDescCurrency.Validators[0].(func(string) error)
	// depositDescNetwork is the schema descriptor for network field.
	depositDescNetwork := depositFields[6].Descriptor()
	// deposit.NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	deposit.NetworkValidator = depositDescNetwork.Validators[0].(func(string) error)
	// depositDescAsset is the schema descriptor for asset field.
	depositDescAsset := depositFields[7].Descriptor()
	// deposit.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	deposit.AssetValidator = depositDescAsset.Validators[0].(func(string) error)
	// depositDescStatus is the schema descriptor for status field.
	depositDescStatus := depositFields[9].Descriptor()
	// deposit.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	deposit.StatusValidator = depositDescStatus.Validators[0].(func(string) error)
	// depositDescConfirmations is the schema descriptor for confirmations field.
	depositDescConfirmations := depositFields[10].Descriptor()
	// deposit.DefaultConfirmations holds the default value on creation for the confirmations field.
	deposit.DefaultConfirmations = depositDescConfirmations.Default.(int)
	// depositDescVersion is the schema descriptor for version field.
	depositDescVersion := depositFields[15].Descriptor()
	// deposit.DefaultVersion holds the default value on creation for the version field.
	deposit.DefaultVersion = depositDescVersion.Default.(int32)
	// depositDescCreatedAt is the schema descriptor for created_at field.
	depositDescCreatedAt := depositFields[16].Descriptor()
	// deposit.DefaultCreatedAt holds the default value on creation for the created_at field.
	deposit.DefaultCreatedAt = depositDescCreatedAt.Default.(func() time.Time)
	// depositDescUpdatedAt is the schema descriptor for updated_at field.
	depositDescUpdatedAt := depositFields[17].Descriptor()
	// deposit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deposit.DefaultUpdatedAt = depositDescUpdatedAt.Default.(func() time.Time)
	// deposit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deposit.UpdateDefaultUpdatedAt = depositDescUpdatedAt.UpdateDefault.(func() time.Time)
	// depositDescID is the schema descriptor for id field.
	depositDescID := depositFields[0].Descriptor()
	// deposit.DefaultID holds the default value on creation for the id field.
	deposit.DefaultID = depositDescID.Default.(func() string)
	depositeventFields := schema.DepositEvent{}.Fields()
	_ = depositeventFields
	// depositeventDescEventType is the schema descriptor for event_type field.
	depositeventDescEventType := depositeventFields[2].Descriptor()
	// depositevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	depositevent.EventTypeValidator = depositeventDescEventType.Validators[0].(func(string) error)
	// depositeventDescFromStatus is the schema descriptor for from_status field.
	depositeventDescFromStatus := depositeventFields[3].Descriptor()
	// depositevent.FromStatusValidator is a validator for the "from_status" field. It is called by the builders before save.
	depositevent.FromStatusValidator = depositeventDescFromStatus.Validators[0].(func(string) error)
	// depositeventDescToStatus is the schema descriptor for to_status field.
	depositeventDescToStatus := depositeventFields[4].Descriptor()
	// depositevent.ToStatusValidator is a validator for the "to_status" field. It is called by the builders before save.
	depositevent.ToStatusValidator = depositeventDescToStatus.Validators[0].(func(string) error)
	// depositeventDescCreatedAt is the schema descriptor for created_at field.
	depositeventDescCreatedAt := depositeventFields[6].Descriptor()
	// depositevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	depositevent.DefaultCreatedAt = depositeventDescCreatedAt.Default.(func() time.Time)
	// depositeventDescID is the schema descriptor for id field.
	depositeventDescID := depositeventFields[0].Descriptor()
	// depositevent.DefaultID holds the default value on creation for the id field.
	depositevent.DefaultID = depositeventDescID.Default.(func() string)
	hotwalletFields := schema.HotWallet{}.Fields()
	_ = hotwalletFields
	// hotwalletDescCurrency is the schema descriptor for currency field.
	hotwalletDescCurrency := hotwalletFields[1].Descriptor()
	// hotwallet.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	hotwallet.CurrencyValidator = hotwalletDescCurrency.Validators[0].(func(string) error)
	// hotwalletDescNetwork is the schema descriptor for network field.
	hotwalletDescNetwork := hotwalletFields[2].Descriptor()
	// hotwallet.NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	hotwallet.NetworkValidator = hotwalletDescNetwork.Validators[0].(func(string) error)
	// hotwalletDescAsset is the schema descriptor for asset field.
	hotwalletDescAsset := hotwalletFields[3].Descriptor()
	// hotwallet.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	hotwallet.AssetValidator = hotwalletDescAsset.Validators[0].(func(string) error)
	// hotwalletDescNextNonce is the schema descriptor for next_nonce field.
	hotwalletDescNextNonce := hotwalletFields[4].Descriptor()
	// hotwallet.DefaultNextNonce holds the default value on creation for the next_nonce field.
	hotwallet.DefaultNextNonce = hotwalletDescNextNonce.Default.(int64)
	// hotwalletDescVersion is the schema descriptor for version field.
	hotwalletDescVersion := hotwalletFields[5].Descriptor()
	// hotwallet.DefaultVersion holds the default value on creation for the version field.
	hotwallet.DefaultVersion = hotwalletDescVersion.Default.(int32)
	// hotwalletDescCreatedAt is the schema descriptor for created_at field.
	hotwalletDescCreatedAt := hotwalletFields[6].Descriptor()
	// hotwallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	hotwallet.DefaultCreatedAt = hotwalletDescCreatedAt.Default.(func() time.Time)
	// hotwalletDescUpdatedAt is the schema descriptor for updated_at field.
	hotwalletDescUpdatedAt := hotwalletFields[7].Descriptor()
	// hotwallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hotwallet.DefaultUpdatedAt = hotwalletDescUpdatedAt.Default.(func() time.Time)
	// hotwallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hotwallet.UpdateDefaultUpdatedAt = hotwalletDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hotwalletDescID is the schema descriptor for id field.
	hotwalletDescID := hotwalletFields[0].Descriptor()
	// hotwallet.DefaultID holds the default value on creation for the id field.
	hotwallet.DefaultID = hotwalletDescID.Default.(func() string)
	withdrawalFields := schema.Withdrawal{}.Fields()
	_ = withdrawalFields
	// withdrawalDescCurrency is the schema descriptor for currency field.
	withdrawalDescCurrency := withdrawalFields[5].Descriptor()
	// withdrawal.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	withdrawal.CurrencyValidator = withdrawalDescCurrency.Validators[0].(func(string) error)
	// withdrawalDescNetwork is the schema descriptor for network field.
	withdrawalDescNetwork := withdrawalFields[6].Descriptor()
	// withdrawal.NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	withdrawal.NetworkValidator = withdrawalDescNetwork.Validators[0].(func(string) error)
	// withdrawalDescAsset is the schema descriptor for asset field.
	withdrawalDescAsset := withdrawalFields[7].Descriptor()
	// withdrawal.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	withdrawal.AssetValidator = withdrawalDescAsset.Validators[0].(func(string) error)
	// withdrawalDescStatus is the schema descriptor for status field.
	withdrawalDescStatus := withdrawalFields[9].Descriptor()
	// withdrawal.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	withdrawal.StatusValidator = withdrawalDescStatus.Validators[0].(func(string) error)
	// withdrawalDescConfirmations is the schema descriptor for confirmations field.
	withdrawalDescConfirmations := withdrawalFields[10].Descriptor()
	// withdrawal.DefaultConfirmations holds the default value on creation for the confirmations field.
	withdrawal.DefaultConfirmations = withdrawalDescConfirmations.Default.(int)
	// withdrawalDescRetryCount is the schema descriptor for retry_count field.
	withdrawalDescRetryCount := withdrawalFields[12].Descriptor()
	// withdrawal.DefaultRetryCount holds the default value on creation for the retry_count field.
	withdrawal.DefaultRetryCount = withdrawalDescRetryCount.Default.(int)
	// withdrawalDescVersion is the schema descriptor for version field.
	withdrawalDescVersion := withdrawalFields[18].Descriptor()
	// withdrawal.DefaultVersion holds the default value on creation for the version field.
	withdrawal.DefaultVersion = withdrawalDescVersion.Default.(int32)
	// withdrawalDescCreatedAt is the schema descriptor for created_at field.
	withdrawalDescCreatedAt := withdrawalFields[19].Descriptor()
	// withdrawal.DefaultCreatedAt holds the default value on creation for the created_at field.
	withdrawal.DefaultCreatedAt = withdrawalDescCreatedAt.Default.(func() time.Time)
	// withdrawalDescUpdatedAt is the schema descriptor for updated_at field.
	withdrawalDescUpdatedAt := withdrawalFields[20].Descriptor()
	// withdrawal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	withdrawal.DefaultUpdatedAt = withdrawalDescUpdatedAt.Default.(func() time.Time)
	// withdrawal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	withdrawal.UpdateDefaultUpdatedAt = withdrawalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// withdrawalDescID is the schema descriptor for id field.
	withdrawalDescID := withdrawalFields[0].Descriptor()
	// withdrawal.DefaultID holds the default value on creation for the id field.
	withdrawal.DefaultID = withdrawalDescID.Default.(func() string)
	withdrawaleventFields := schema.WithdrawalEvent{}.Fields()
	_ = withdrawaleventFields
	// withdrawaleventDescEventType is the schema descriptor for event_type field.
	withdrawaleventDescEventType := withdrawaleventFields[2].Descriptor()
	// withdrawalevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	withdrawalevent.EventTypeValidator = withdrawaleventDescEventType.Validators[0].(func(string) error)
	// withdrawaleventDescFromStatus is the schema descriptor for from_status field.
	withdrawaleventDescFromStatus := withdrawaleventFields[3].Descriptor()
	// withdrawalevent.FromStatusValidator is a validator for the "from_status" field. It is called by the builders before save.
	withdrawalevent.FromStatusValidator = withdrawaleventDescFromStatus.Validators[0].(func(string) error)
	// withdrawaleventDescToStatus is the schema descriptor for to_status field.
	withdrawaleventDescToStatus := withdrawaleventFields[4].Descriptor()
	// withdrawalevent.ToStatusValidator is a validator for the "to_status" field. It is called by the builders before save.
	withdrawalevent.ToStatusValidator = withdrawaleventDescToStatus.Validators[0].(func(string) error)
	// withdrawaleventDescCreatedAt is the schema descriptor for created_at field.
	withdrawaleventDescCreatedAt := withdrawaleventFields[6].Descriptor()
	// withdrawalevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	withdrawalevent.DefaultCreatedAt = withdrawaleventDescCreatedAt.Default.(func() time.Time)
	// withdrawaleventDescID is the schema descriptor for id field.
	withdrawaleventDescID := withdrawaleventFields[0].Descriptor()
	// withdrawalevent.DefaultID holds the default value on creation for the id field.
	withdrawalevent.DefaultID = withdrawaleventDescID.Default.(func() string)
}
