// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/predicate"
	"crypto-payment-service/ent/withdrawalevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WithdrawalEventDelete is the builder for deleting a WithdrawalEvent entity.
type WithdrawalEventDelete struct {
	config
	hooks    []Hook
	mutation *WithdrawalEventMutation
}

// Where appends a list predicates to the WithdrawalEventDelete builder.
func (_d *WithdrawalEventDelete) Where(ps ...predicate.WithdrawalEvent) *WithdrawalEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WithdrawalEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WithdrawalEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WithdrawalEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(withdrawalevent.Table, sqlgraph.NewFieldSpec(withdrawalevent.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WithdrawalEventDeleteOne is the builder for deleting a single WithdrawalEvent entity.
type WithdrawalEventDeleteOne struct {
	_d *WithdrawalEventDelete
}

// Where appends a list predicates to the WithdrawalEventDelete builder.
func (_d *WithdrawalEventDeleteOne) Where(ps ...predicate.WithdrawalEvent) *WithdrawalEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WithdrawalEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{withdrawalevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WithdrawalEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
