// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/customer"
	"crypto-payment-service/ent/predicate"
	"crypto-payment-service/ent/withdrawal"
	"crypto-payment-service/ent/withdrawalevent"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WithdrawalQuery is the builder for querying Withdrawal entities.
type WithdrawalQuery struct {
	config
	ctx          *QueryContext
	order        []withdrawal.OrderOption
	inters       []Interceptor
	predicates   []predicate.Withdrawal
	withCustomer *CustomerQuery
	withEvents   *WithdrawalEventQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WithdrawalQuery builder.
func (_q *WithdrawalQuery) Where(ps ...predicate.Withdrawal) *WithdrawalQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WithdrawalQuery) Limit(limit int) *WithdrawalQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WithdrawalQuery) Offset(offset int) *WithdrawalQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WithdrawalQuery) Unique(unique bool) *WithdrawalQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WithdrawalQuery) Order(o ...withdrawal.OrderOption) *WithdrawalQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCustomer chains the current query on the "customer" edge.
func (_q *WithdrawalQuery) QueryCustomer() *CustomerQuery {
	query := (&CustomerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(withdrawal.Table, withdrawal.FieldID, selector),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, withdrawal.CustomerTable, withdrawal.CustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *WithdrawalQuery) QueryEvents() *WithdrawalEventQuery {
	query := (&WithdrawalEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(withdrawal.Table, withdrawal.FieldID, selector),
			sqlgraph.To(withdrawalevent.Table, withdrawalevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, withdrawal.EventsTable, withdrawal.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Withdrawal entity from the query.
// Returns a *NotFoundError when no Withdrawal was found.
func (_q *WithdrawalQuery) First(ctx context.Context) (*Withdrawal, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{withdrawal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WithdrawalQuery) FirstX(ctx context.Context) *Withdrawal {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Withdrawal ID from the query.
// Returns a *NotFoundError when no Withdrawal ID was found.
func (_q *WithdrawalQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{withdrawal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WithdrawalQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Withdrawal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Withdrawal entity is found.
// Returns a *NotFoundError when no Withdrawal entities are found.
func (_q *WithdrawalQuery) Only(ctx context.Context) (*Withdrawal, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{withdrawal.Label}
	default:
		return nil, &NotSingularError{withdrawal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WithdrawalQuery) OnlyX(ctx context.Context) *Withdrawal {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Withdrawal ID in the query.
// Returns a *NotSingularError when more than one Withdrawal ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WithdrawalQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{withdrawal.Label}
	default:
		err = &NotSingularError{withdrawal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WithdrawalQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Withdrawals.
func (_q *WithdrawalQuery) All(ctx context.Context) ([]*Withdrawal, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Withdrawal, *WithdrawalQuery]()
	return withInterceptors[[]*Withdrawal](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WithdrawalQuery) AllX(ctx context.Context) []*Withdrawal {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Withdrawal IDs.
func (_q *WithdrawalQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(withdrawal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WithdrawalQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WithdrawalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WithdrawalQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WithdrawalQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WithdrawalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WithdrawalQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WithdrawalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WithdrawalQuery) Clone() *WithdrawalQuery {
	if _q == nil {
		return nil
	}
	return &WithdrawalQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]withdrawal.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Withdrawal{}, _q.predicates...),
		withCustomer: _q.withCustomer.Clone(),
		withEvents:   _q.withEvents.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCustomer tells the query-builder to eager-load the nodes that are connected to
// the "customer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WithdrawalQuery) WithCustomer(opts ...func(*CustomerQuery)) *WithdrawalQuery {
	query := (&CustomerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomer = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WithdrawalQuery) WithEvents(opts ...func(*WithdrawalEventQuery)) *WithdrawalQuery {
	query := (&WithdrawalEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CustomerID string `json:"customer_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Withdrawal.Query().
//		GroupBy(withdrawal.FieldCustomerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WithdrawalQuery) GroupBy(field string, fields ...string) *WithdrawalGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WithdrawalGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = withdrawal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CustomerID string `json:"customer_id,omitempty"`
//	}
//
//	client.Withdrawal.Query().
//		Select(withdrawal.FieldCustomerID).
//		Scan(ctx, &v)
func (_q *WithdrawalQuery) Select(fields ...string) *WithdrawalSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WithdrawalSelect{WithdrawalQuery: _q}
	sbuild.label = withdrawal.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WithdrawalSelect configured with the given aggregations.
func (_q *WithdrawalQuery) Aggregate(fns ...AggregateFunc) *WithdrawalSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WithdrawalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !withdrawal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WithdrawalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Withdrawal, error) {
	var (
		nodes       = []*Withdrawal{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCustomer != nil,
			_q.withEvents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Withdrawal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Withdrawal{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCustomer; query != nil {
		if err := _q.loadCustomer(ctx, query, nodes, nil,
			func(n *Withdrawal, e *Customer) { n.Edges.Customer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *Withdrawal) { n.Edges.Events = []*WithdrawalEvent{} },
			func(n *Withdrawal, e *WithdrawalEvent) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WithdrawalQuery) loadCustomer(ctx context.Context, query *CustomerQuery, nodes []*Withdrawal, init func(*Withdrawal), assign func(*Withdrawal, *Customer)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Withdrawal)
	for i := range nodes {
		fk := nodes[i].CustomerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(customer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "customer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WithdrawalQuery) loadEvents(ctx context.Context, query *WithdrawalEventQuery, nodes []*Withdrawal, init func(*Withdrawal), assign func(*Withdrawal, *WithdrawalEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Withdrawal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(withdrawalevent.FieldWithdrawalID)
	}
	query.Where(predicate.WithdrawalEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(withdrawal.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WithdrawalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "withdrawal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *WithdrawalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WithdrawalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(withdrawal.Table, withdrawal.Columns, sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, withdrawal.FieldID)
		for i := range fields {
			if fields[i] != withdrawal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCustomer != nil {
			_spec.Node.AddColumnOnce(withdrawal.FieldCustomerID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WithdrawalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(withdrawal.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = withdrawal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *WithdrawalQuery) ForUpdate(opts ...sql.LockOption) *WithdrawalQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *WithdrawalQuery) ForShare(opts ...sql.LockOption) *WithdrawalQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// WithdrawalGroupBy is the group-by builder for Withdrawal entities.
type WithdrawalGroupBy struct {
	selector
	build *WithdrawalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WithdrawalGroupBy) Aggregate(fns ...AggregateFunc) *WithdrawalGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WithdrawalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WithdrawalQuery, *WithdrawalGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WithdrawalGroupBy) sqlScan(ctx context.Context, root *WithdrawalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WithdrawalSelect is the builder for selecting fields of Withdrawal entities.
type WithdrawalSelect struct {
	*WithdrawalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WithdrawalSelect) Aggregate(fns ...AggregateFunc) *WithdrawalSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WithdrawalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WithdrawalQuery, *WithdrawalSelect](ctx, _s.WithdrawalQuery, _s, _s.inters, v)
}

func (_s *WithdrawalSelect) sqlScan(ctx context.Context, root *WithdrawalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
