// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crypto-payment-service/ent/withdrawal"
	"crypto-payment-service/ent/withdrawalevent"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WithdrawalEventCreate is the builder for creating a WithdrawalEvent entity.
type WithdrawalEventCreate struct {
	config
	mutation *WithdrawalEventMutation
	hooks    []Hook
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_c *WithdrawalEventCreate) SetWithdrawalID(v string) *WithdrawalEventCreate {
	_c.mutation.SetWithdrawalID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *WithdrawalEventCreate) SetEventType(v string) *WithdrawalEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetFromStatus sets the "from_status" field.
func (_c *WithdrawalEventCreate) SetFromStatus(v string) *WithdrawalEventCreate {
	_c.mutation.SetFromStatus(v)
	return _c
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_c *WithdrawalEventCreate) SetNillableFromStatus(v *string) *WithdrawalEventCreate {
	if v != nil {
		_c.SetFromStatus(*v)
	}
	return _c
}

// SetToStatus sets the "to_status" field.
func (_c *WithdrawalEventCreate) SetToStatus(v string) *WithdrawalEventCreate {
	_c.mutation.SetToStatus(v)
	return _c
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_c *WithdrawalEventCreate) SetNillableToStatus(v *string) *WithdrawalEventCreate {
	if v != nil {
		_c.SetToStatus(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *WithdrawalEventCreate) SetMetadata(v map[string]interface{}) *WithdrawalEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WithdrawalEventCreate) SetCreatedAt(v time.Time) *WithdrawalEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WithdrawalEventCreate) SetNillableCreatedAt(v *time.Time) *WithdrawalEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WithdrawalEventCreate) SetID(v string) *WithdrawalEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WithdrawalEventCreate) SetNillableID(v *string) *WithdrawalEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetWithdrawal sets the "withdrawal" edge to the Withdrawal entity.
func (_c *WithdrawalEventCreate) SetWithdrawal(v *Withdrawal) *WithdrawalEventCreate {
	return _c.SetWithdrawalID(v.ID)
}

// Mutation returns the WithdrawalEventMutation object of the builder.
func (_c *WithdrawalEventCreate) Mutation() *WithdrawalEventMutation {
	return _c.mutation
}

// Save creates the WithdrawalEvent in the database.
func (_c *WithdrawalEventCreate) Save(ctx context.Context) (*WithdrawalEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WithdrawalEventCreate) SaveX(ctx context.Context) *WithdrawalEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WithdrawalEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WithdrawalEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WithdrawalEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := withdrawalevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := withdrawalevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WithdrawalEventCreate) check() error {
	if _, ok := _c.mutation.WithdrawalID(); !ok {
		return &ValidationError{Name: "withdrawal_id", err: errors.New(`ent: missing required field "WithdrawalEvent.withdrawal_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "WithdrawalEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := withdrawalevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "WithdrawalEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FromStatus(); ok {
		if err := withdrawalevent.FromStatusValidator(v); err != nil {
			return &ValidationError{Name: "from_status", err: fmt.Errorf(`ent: validator failed for field "WithdrawalEvent.from_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ToStatus(); ok {
		if err := withdrawalevent.ToStatusValidator(v); err != nil {
			return &ValidationError{Name: "to_status", err: fmt.Errorf(`ent: validator failed for field "WithdrawalEvent.to_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WithdrawalEvent.created_at"`)}
	}
	if len(_c.mutation.WithdrawalIDs()) == 0 {
		return &ValidationError{Name: "withdrawal", err: errors.New(`ent: missing required edge "WithdrawalEvent.withdrawal"`)}
	}
	return nil
}

func (_c *WithdrawalEventCreate) sqlSave(ctx context.Context) (*WithdrawalEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WithdrawalEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WithdrawalEventCreate) createSpec() (*WithdrawalEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &WithdrawalEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(withdrawalevent.Table, sqlgraph.NewFieldSpec(withdrawalevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(withdrawalevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.FromStatus(); ok {
		_spec.SetField(withdrawalevent.FieldFromStatus, field.TypeString, value)
		_node.FromStatus = &value
	}
	if value, ok := _c.mutation.ToStatus(); ok {
		_spec.SetField(withdrawalevent.FieldToStatus, field.TypeString, value)
		_node.ToStatus = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(withdrawalevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(withdrawalevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.WithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   withdrawalevent.WithdrawalTable,
			Columns: []string{withdrawalevent.WithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WithdrawalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WithdrawalEventCreateBulk is the builder for creating many WithdrawalEvent entities in bulk.
type WithdrawalEventCreateBulk struct {
	config
	err      error
	builders []*WithdrawalEventCreate
}

// Save creates the WithdrawalEvent entities in the database.
func (_c *WithdrawalEventCreateBulk) Save(ctx context.Context) ([]*WithdrawalEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WithdrawalEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WithdrawalEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WithdrawalEventCreateBulk) SaveX(ctx context.Context) []*WithdrawalEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WithdrawalEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WithdrawalEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
