// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crypto-payment-service/ent/withdrawal"
	"crypto-payment-service/ent/withdrawalevent"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WithdrawalEvent is the model entity for the WithdrawalEvent schema.
type WithdrawalEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// WithdrawalID holds the value of the "withdrawal_id" field.
	WithdrawalID string `json:"withdrawal_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// FromStatus holds the value of the "from_status" field.
	FromStatus *string `json:"from_status,omitempty"`
	// ToStatus holds the value of the "to_status" field.
	ToStatus *string `json:"to_status,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WithdrawalEventQuery when eager-loading is set.
	Edges        WithdrawalEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WithdrawalEventEdges holds the relations/edges for other nodes in the graph.
type WithdrawalEventEdges struct {
	// Withdrawal holds the value of the withdrawal edge.
	Withdrawal *Withdrawal `json:"withdrawal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WithdrawalOrErr returns the Withdrawal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WithdrawalEventEdges) WithdrawalOrErr() (*Withdrawal, error) {
	if e.Withdrawal != nil {
		return e.Withdrawal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: withdrawal.Label}
	}
	return nil, &NotLoadedError{edge: "withdrawal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WithdrawalEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case withdrawalevent.FieldMetadata:
			values[i] = new([]byte)
		case withdrawalevent.FieldID, withdrawalevent.FieldWithdrawalID, withdrawalevent.FieldEventType, withdrawalevent.FieldFromStatus, withdrawalevent.FieldToStatus:
			values[i] = new(sql.NullString)
		case withdrawalevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WithdrawalEvent fields.
func (_m *WithdrawalEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case withdrawalevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case withdrawalevent.FieldWithdrawalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field withdrawal_id", values[i])
			} else if value.Valid {
				_m.WithdrawalID = value.String
			}
		case withdrawalevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case withdrawalevent.FieldFromStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_status", values[i])
			} else if value.Valid {
				_m.FromStatus = new(string)
				*_m.FromStatus = value.String
			}
		case withdrawalevent.FieldToStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_status", values[i])
			} else if value.Valid {
				_m.ToStatus = new(string)
				*_m.ToStatus = value.String
			}
		case withdrawalevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case withdrawalevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WithdrawalEvent.
// This includes values selected through modifiers, order, etc.
func (_m *WithdrawalEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWithdrawal queries the "withdrawal" edge of the WithdrawalEvent entity.
func (_m *WithdrawalEvent) QueryWithdrawal() *WithdrawalQuery {
	return NewWithdrawalEventClient(_m.config).QueryWithdrawal(_m)
}

// Update returns a builder for updating this WithdrawalEvent.
// Note that you need to call WithdrawalEvent.Unwrap() before calling this method if this WithdrawalEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WithdrawalEvent) Update() *WithdrawalEventUpdateOne {
	return NewWithdrawalEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WithdrawalEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WithdrawalEvent) Unwrap() *WithdrawalEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WithdrawalEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WithdrawalEvent) String() string {
	var builder strings.Builder
	builder.WriteString("WithdrawalEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("withdrawal_id=")
	builder.WriteString(_m.WithdrawalID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	if v := _m.FromStatus; v != nil {
		builder.WriteString("from_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ToStatus; v != nil {
		builder.WriteString("to_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WithdrawalEvents is a parsable slice of WithdrawalEvent.
type WithdrawalEvents []*WithdrawalEvent
